### ISSUE TITLE
If I'm operating a node, can I browse the files that my node is hosting?

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/faq#10]
Yes, you can browse the _blocks_ that your node is hosting. Files are an abstraction built on top of the merkledag. All data in ipfs is stored as content addressed blocks (so there are no filenames unless you have the directory block containing said file).

**Comment by jbenet** [comment]
- You can look at all the local refs with `ipfs refs local`
- The `webui` uses this to list files.
- (planned) we will have listings of the roots to make the content more navigable.
- (planned) we will have something like `ipfs files find` equivalent to unix `find`.

**Comment by whyrusleeping** [comment]
Some code that I have for viewing the `roots` (roots of merkledags, normally files or directories)

https://gist.github.com/whyrusleeping/9f2c83f3feed340e21ac

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/if-im-operating-a-node-can-i-browse-the-files-that-my-node-is-hosting/380.
