### ISSUE TITLE
Disc Space Cost Function

### ISSUE THREAD

**Issue by ibnesayeed** [ipfs/faq#101]
Given a UNIX directory path with handful of files in it of varying sizes, is there any way to estimate how much storage space will be needed in the IPFS Data directory if everything is added to it? Is there a function in which we can put these parameters and calculate the storage requirement?

**Comment by Kubuxu** [comment]
It can be from 1.2 times more to anywhere less.

It is because IPFS adds some overhead but it also performs deduplication.
Good example is cdnjs, the directory in linux file system is 21GB, the IPFS data directory after adding it is 15GB.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/disc-space-cost-function/450
