### ISSUE TITLE
Can routing bridge across transports

### ISSUE THREAD

**Issue by novocodev** [ipfs/faq#103]
Does IPFS bridge the routing protocol across transports, e.g. if I have a number of IoT devices in my home that work over Bluetooth, and I have a home hub that supports Bluetooth and has access to the Internet.

If all devices are running IPFS can I interact with the IoT devices via a mobile phone running IPFS with an internet connection. Will the home hub bridge the routing protocol across transports so that the IoT devices are accessible from my mobile device?

**Comment by RichardLitt** [comment]
Good question! @diasdavid, I think you might be best to answer this. Thoughts?

**Comment by vitzli** [comment]
I am not a developer for ipfs, but according to [Issue #7](https://github.com/ipfs/faq/issues/7) I would say 'yes, it will be possible in future', AFAIK right now ipfs only supports IP addressing, however, if it is possible to run IP-over-BT - I don't see any reasons that would interfere with it. I don't know if ipfs could work with non-IP networks like i2p and tor, but it should be possible to run non-anonymous gateways on such networks.

**Comment by daviddias** [comment]
@novocodev traffic can be relayed/line switched/packet switch across multiple transports, it is something we designed in the core of libp2p to enable more interoperability between different devices with different capabilities. However these features haven't been released yet.

**Comment by novocodev** [comment]
@diasdavid this is great news, I'm still early in project development/design so more interested in planned feature support than implementation right now.

**Comment by Kubuxu** [comment]
Please leave this issue open. As FAQ question it is important for it to be easily visible.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/can-routing-bridge-across-transports/448.
