### ISSUE TITLE
Legal takedown request compliance

### ISSUE THREAD

**Issue by josephholsten** [ipfs/faq#106]
Many legal jurisdictions may mandate that certain content be taken down:
- Court injunction
- DMCA takedown notices, like https://github.com/github/dmca
- Roskomnadzor requests, like https://github.com/github/roskomnadzor

How may an IPFS service provider comply with these requests?

**Comment by josephholsten** [comment]
some related info exists on https://github.com/ipfs/faq/issues/9

**Comment by jbenet** [comment]
@josephholsten see https://github.com/ipfs/faq/issues/36#issuecomment-140567411

**Comment by josephholsten** [comment]
@jbenet nice! Eventually I'd like to flesh this out with public gateway operator guides for "How to verify you're using the appropriate denylists for your jurisdiction" and "So you've just received a DMCA takedown notice, here's how to respond"

**Comment by malakai97** [comment]
It's useful to realize that even with http takedown notices only apply to a single server.  The users that have already received the content that was taken down still have that content, and there is nothing technical in place to prevent them from making it available again (nor does the takedown notice apply to them in many jurisdictions).

IPFS just makes this truth obvious.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/legal-takedown-request-compliance/295.
