### ISSUE TITLE
How does IPFS relate with Ethereum?

### ISSUE THREAD

**Issue by teaalltr** [ipfs/faq#107]
Could you give an overview of how these two technologies could work together (if possible at all)?
Can Ethereum lay upon IPFS?

**Comment by RichardLitt** [comment]
That's a pretty abstract question. AFAIK, IPFS can be a storage layer for Ethereum. The blockchain can be stored in IPFS, sure. You can't do the computing on IPFS, though (it's a file system, or more accurately, just a DAG). You can build apps on IPFS that can be run, but they won't be executed (like Ethereum). 

I would read around a bit more. Not sure where for now, though, so I'm assigning @jbenet to this.

**Comment by stevenh512** [comment]
Some Ethereum developers are basically using IPFS as a stand-in for their own distributed filesystem (SWARM) until it's ready. If you're building a distributed app for Ethereum, the entire backend lives on the blockchain as smart contracts. If you decide your app should have a HTML/javascript frontend, that's where IPFS comes in, you can publish the static HTML and javascript to IPFS just as easily as you could publish it to a web server or GitHub Pages.

Aside from that, and the fact that they're both decentralized peer-to-peer protocols, as far as I know they're not related.

**Comment by laygr** [comment]
Is it possible to ONLY allow an ethereum contract to upload files? If so, can you give any pointer to the relevant docs?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-does-ipfs-relate-with-ethereum/414.
