### ISSUE TITLE
Is it possible to attach a file name to a ipfs.io URL?

### ISSUE THREAD

**Issue by stefanv** [ipfs/faq#109]
E.g., if I have

http://ipfs.io/ipfs/QmRZ97nBLWfjB9FcFLH48RuijWQwk3JUvRFrn1Wr5suZ11

Is there a way to make ipfs.io generate a Content-Disposition + filename header?

**Comment by ghost** [comment]
Only if you've wrapped it in a directory -- e.g.:

``` sh
> ipfs add -w file.txt
> ipfs add -r .
```

**Comment by salsa-dev** [comment]
I'm wrapping directories with:
`ipfs add -rw directory/`
which is exactly what I need.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-it-possible-to-attach-a-file-name-to-a-ipfs-io-url/474
