### ISSUE TITLE
Can I control the amount of storage/bandwidth dedicated to IPFS?

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/faq#11]
Currently, no, but these are features that are planned for the near future.

**Comment by voidzero** [comment]
In the meantime it might be interesting to use ipfs together with firejail. With firejail it is possible to run ipfs in its own namespaces, with a dedicated macvlan device, of which traffic can be shaped. There are additional benefits as well, like routing only ipfs through a VPN, using a specific IPv4 or IPv6 address, chrooting, and securing with seccomp and capability limiting.

**Comment by llopv** [comment]
You can define the maximum allowed storage in the datastore at `.ipfs/config` file. Default is 10GB.

**Comment by ghost** [comment]
> You can define the maximum allowed storage in the datastore at .ipfs/config file. Default is 10GB.

That setting doesn't actually put a hard limit on storage usage -- right now it's only used in relation to garbage collection.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/can-i-control-the-amount-of-storage-bandwidth-dedicated-to-ipfs/395.
