### ISSUE TITLE
large files question about duplication 

### ISSUE THREAD

**Issue by icf20** [ipfs/faq#110]
I have a question about the block part, if i take a 100MB video and add it into IPFS, then a person take that video and cut the file in half and add the file again, will duplicate the 50% of the blocks or will share the blocks ? 

(first posted on the wrong place https://github.com/ipfs/go-ipfs/issues/2575)

so my new question is there any chance to save space and dont duplicate blocks even if is 1%

**Comment by jurgen-kluft** [comment]
As far as i understand IPFS the default block-size is 256KiB, so the answer would be that there is de-duplication happening assuming the 'cut the file in half' means that the part that is left is binary wise the same as its part in the original video file.

'added':
Actually you can make it visible to see for yourself, when you add a large file you get a hash-link, you can use that hash-link to list the internals. You can also do that for the part you added, if the hashes of all the parts are the same then the answer is that chunks are shared.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/large-files-question-about-duplication/442
