### ISSUE TITLE
File encryption built into IPFS?

### ISSUE THREAD

**Issue by matthewrobertbell** [ipfs/faq#116]
Hi,

I googled around for this, but didn't find anything: Are there plans to allow adding and getting of ipfs objects with transparent encryption of the data by IPFS?

For example: "ipfs add file.txt --password=abc" "ipfs get <hash> --password=abc"

**Comment by lidel** [comment]
You can use external tools to achieve it: write a wrapper script that encrypts file before adding it to IPFS.

Basic symmetrical encryption from your example can be done via `openssl`, for example:

``` bash
# encrypt
openssl aes-256-cbc -salt -in plain.txt  -out encrypted.txt

# decrypt
openssl aes-256-cbc -d -in encrypted.txt -out decrypted.txt 
```

For asymmetrical use `gpg`. 

Follow Unix philosophy "Do One Thing and Do It Well".

**Comment by bronger** [comment]
But the IPFS whitepaper mentiones “object-level cryptography”.  Has this plan been dropped?

**Comment by Kubuxu** [comment]
No it hasn't, it is generally written down as `keystore`, see: https://github.com/ipfs/specs/tree/master/keystore

As it depends on IPLD and keychain (where the latter hasn't been touched yet as it also depends on IPLD) it will be some time until it is usable.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/file-encryption-built-into-ipfs/323.
