### ISSUE TITLE
Decoupled serving and signing

### ISSUE THREAD

**Issue by omphalos** [ipfs/faq#117]
For mutable storage, my understanding is that you run a server, and this server signs pointers to content-addressed IPFS entries.

Is it possible for one party (such as a web browser, mobile device, IoT device) to sign a pointer and publish this signed pointer over IPFS via a willing intermediary?  For example: a web application signs a message pointing their key to such-and-such content, then sends this signed pointer to an IPFS node.  Then this IPFS node publishes this signed pointer on the application's behalf over IPNS.  (This would all be done in a way such that the IPFS/IPNS node does not have knowledge of the private key managed by the web application.)

In case this is not possible, is there any plan to make it possible in the future?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/decoupled-serving-and-signing/398
