### ISSUE TITLE
Security policy and secrecy

### ISSUE THREAD

**Issue by geebotron** [ipfs/faq#118]
I'm interested in your security policy.

On [this page](https://github.com/ipfs/go-ipfs) you request serious security vulnerabilities in IPFS be reported privately and not made public. This is in contrast to, say, the [OpenBSD security policy](http://www.openbsd.org/security.html) which encourages full public disclosure.

I'm interested to know how you think your policy improves the security of someone who hosts a "live" IPFS node, given that any vulnerability you have been made aware of, may also have been circulated among other "organizations"?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/security-policy-and-secrecy/348
