### ISSUE TITLE
Does IPFS provide any guarantees about anonymity?

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/faq#12]
ipfs makes no claims about anonymity, the default routing system (the DHT) makes it very easy to query the ip address of a peer hosting any given block. Down the road we plan on implementing a TOR-like routing system that may provide anonymity.

**Comment by jbenet** [comment]
We will be enumerating all parts of the protocol where anonymity is concerned, so that different modules can be built. (note that there are strong tradeoffs, which is why ipfs choses to be modular)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/does-ipfs-provide-any-guarantees-about-anonymity/387.
