### ISSUE TITLE
Accessing non-existing hash key using REST

### ISSUE THREAD

**Issue by biljanaLukovic** [ipfs/faq#120]
I have install and configured ipfs version 0.4.0. Happy path works eg. I can put an item into ipfs and retrieve it by produced hash. However, the service does not return when 'cat' looks for non existing hash code.
Example with valid hash code:
http://127.0.0.1:5001/api/v0/cat/QmckRHhKxcrp4Y2miz9hpAzFk2fepenrQCT524VYrL9LKY
Any changes in the supplied hash code will cause server to hung.
Attached is my config file.
Thanks 
B
[config.txt](https://github.com/ipfs/faq/files/259918/config.txt)

**Comment by ghost** [comment]
The daemon doesn't know that the requested object _does not_ exist. It has no way to know it, and just keeps looking for it in the network.

**Comment by biljanaLukovic** [comment]
Does this mean that web service will not return any response (like status or time out)?
Thanks

**Comment by ghost** [comment]
It will eventually time out. The public gateway at ipfs.io times out after 30 minutes, I'm not sure what the timeout of the daemon's gateway itself is -- definitely more than 30 minutes though.

Do you want to be able to tell if an object does _not_ exist? You could specify a request timeout with the HTTP/REST library or tool you are using.

**Comment by whyrusleeping** [comment]
You can also add a timeout yourself with the `timeout` option, for example:
`timeout=30s`

**Comment by biljanaLukovic** [comment]
Thank you lgierth. I set the read timeout on the connection and get immediate response

**Comment by madavieb** [comment]
This issue has been moved https://discuss.ipfs.io/t/accessing-non-existing-hash-key-using-rest/472.
