### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by biljanaLukovic** [ipfs/faq#121]
What is the recommended way to achieve high availability? I want to have two nodes exposing IPFS WEB service. If one node goes down I want to make sure that data is available through the other.
Thanks

**Comment by harlantwood** [comment]
Great question.

**Comment by ghost** [comment]
Regarding high availability of data, there are concrete plans for an ipfs-cluster tool: https://github.com/ipfs/notes/issues/58

High availability for the gateway can be achieved by e.g. round-robin DNS, or load balancing.

**Comment by RichardLitt** [comment]
@lgierth What can @biljanaLukovic do right now to ensure high availability? Is there a guide?

**Comment by ghost** [comment]
+1 Currently I'm spinning IPFS nodes behind an Nginx server. I was recommended this package to achieve consensus among nodes. Haven't checked it yet. Here it is:

https://github.com/pipermerriam/ipfs-persistence-consortium/

Let me know what have you found so far, so we can work together on a first approach to solve this problem quickly.

**Comment by salsa-dev** [comment]
+1 I'm also willing to build a service to provide data from libraries through ipfs gateway. The current problem is in synching all the data on two ipfs nodes and pushing data from other nodes. I'm aware of several solutions which haven't tried yet:
- A consortium to help persist IPFS objects https://github.com/pipermerriam/ipfs-persistence-consortium
- PinCoop is a set of API endpoints and WebUI for adding public daemons, retrieve a list of all of them and to add hashes to be pinned on those public daemons. https://github.com/victorbjelkholm/pincoop
- IPFS replication service with one line of unix shell code!  https://gist.github.com/kyledrake/e8e2a583741b3bb8237e

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/high-availability/374.
