### ISSUE TITLE
Log of blocks sent to other peers?

### ISSUE THREAD

**Issue by kevina** [ipfs/faq#122]
Is there currently any way to log blocks that are sent to other peers?

I am trying to get an IPFS equivalent to an http access log.  I know it won't be the same as IPFS is distributed, but it will still be useful.

The best thing I can determine is to use `ipfs log level bitswap info`. But I am not sure that will get everything.

**Comment by whyrusleeping** [comment]
Not really easily, but you can use `ipfs log tail` and filter by events that are `Bitswap.TaskWorker.Loop`, which should tell you every time you sent a block to a peer.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/log-of-blocks-sent-to-other-peers/356
