### ISSUE TITLE
How can I configure IPFS node to use SHA3?

### ISSUE THREAD

**Issue by biljanaLukovic** [ipfs/faq#124]
If node was configured with SHA3 will  SHA3 be used for encoding? There are indication that SHA2 was hard-coded in the current version.

**Comment by whyrusleeping** [comment]
@biljanaLukovic yes, it is currently hard coded. but you can change the value here: https://github.com/ipfs/go-ipfs-util/blob/master/util.go#L20 

and then update that dependency in go-ipfs (or, in go-ipfs run `gx-go rewrite --undo go-ipfs-util`for testing it out real quick).

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-can-i-configure-ipfs-node-to-use-sha3/286
