### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by bronger** [ipfs/faq#126]
How is it realised in IPFS that a certain file is only accessed by certain people?  I saw UNIX-like permissions in the white paper of IPLD, but how is this enforced?

**Comment by jcalfee** [comment]
You probably need to encrypt the file and use a shared secret.  This probably is not the job of the IPFS system..

**Comment by bronger** [comment]
In the meantime, I've got the impression that there are plans for more sophisticated access control in the future.  But there doesn't seem to be anything concrete yet.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/access-control/285.
