### ISSUE TITLE
IPFS across temporary links

### ISSUE THREAD

**Issue by jantypas** [ipfs/faq#127]
A question for the IPFS experts.   I am looking at remote IPFS nodes.  In some locations, we may have local "IPFS clusters" on Wifi, but the long-haul links are spotty.   Consider the following usage case:

A local school district might have multiple IPFS nodes which communicate across local Wifi.   Everything works just fine.  
The school districts will connect twice a day on long-haul IP links.  I am assuming during that connection, the IPFS nodes will synchronize

Can I do this?

**Comment by matthewrobertbell** [comment]
What do you mean by synchronize? As long as they know of each other and the links work, they can communicate and exchange data if someone requests it (or automatic DHT propagation).

**Comment by jantypas** [comment]
I am thinking of the following scenario.   This is a very rural school 
in Africa.   They may only have mobile connections to the net, say, 
twice a day.   Off-net, they'd be living off a cached-version of IPFS 
until the twice-a-day synchronization.

------ Original Message ------

**Comment by Kubuxu** [comment]
@jantypas it could work, you would just have to know sites you would like to synchronize.
Then as connection comes in, you would requires the m from IPFS network.
Also for now I would wait as we are still working on making IPFS less transfer hungry.

**Comment by jcalfee** [comment]
Wouldn't you take all the hashes you wanted to sync and grab that file then PIN them in somewhere in the network that needed to download them?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/ipfs-across-temporary-links/324.
