### ISSUE TITLE
How can IPFS support cyclic content?

### ISSUE THREAD

**Issue by magcius** [ipfs/faq#129]
Let's say I want to host a website on IPFS and have two web pages, and both of them link to each other.

Since IPFS is content-addressed, that means that each page's link would have to be a link to the other page's hash, correct? And since the other web page links to me, I have to find two dependent fixed points of hashes...

I didn't see any way of doing name to content mapping in IPFS, which is the system that Freenet, etc. all use to solve this problem.

**Comment by harlantwood** [comment]
Check out IPNS: https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/ipns/readme.md

**Comment by magcius** [comment]
Yes, I saw that, but since you only get a single blob per name, I didn't think it was intended for this use case, but simply to point to an index file. Additionally, you don't get content permanence &mdash; the thing I link to would be the latest version of whatever I publish at my webpage, not the hash at the time of upload.

I was imagining a system where: the entire bundle was the content-addressed unit, and links happened in there based on name. So my website would be the content-addressed, hashable unit, and all HTML pages, bundled resources, etc. would be identified by relative links inside that.

But maybe that's not how IPFS wants to work.

**Comment by harlantwood** [comment]
Works as long as you have relative links, eg: https://ipfs.io/ipfs/QmavE42xtK1VovJFVTVkCR5Jdf761QWtxmvak9Zx718TVr/index.html

**Comment by whyrusleeping** [comment]
@magcius relative links in webpages work just fine. the ipfs.io webpage is actually served through ipfs via `/ipns/ipfs.io`

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 10:33:45AM -0700, Jeromy Johnson wrote:

> @magcius relative links in webpages work just fine. the ipfs.io
> webpage is actually served through ipfs via `/ipns/ipfs.io`

This breaks the “my IPFS tooling can walk the graph” without teaching
your tooling about HTML.  But if the HTML links only point inside a
directory structure, then being able to walk an IPFS directory
structure is sufficent for a complete snapshot and @magcius' content
permanence.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-can-ipfs-support-cyclic-content/320.
