### ISSUE TITLE
How does an ipfs app update itself?

### ISSUE THREAD

**Issue by rdrey** [ipfs/faq#13]
If I wanted to host an app completely on ipfs (no external servers and feeds), I'd share the hashed address of my app, right?

How do I update any content in the app? How do I update the app itself? I'm assuming that any change to my app will result in a new hash / address, which I will have to distribute via an out-of-band channel?

Thanks, interesting project!

**Comment by jbenet** [comment]
> If I wanted to host an app completely on ipfs (no external servers and feeds), I'd share the hashed address of my app, right?

Yes.

> How do I update any content in the app? How do I update the app itself? I'm assuming that any change to my app will result in a new hash / address, which I will have to distribute via an out-of-band channel?

Yes, for `/ipfs/...` paths. But  `/<ipns>/...` paths are _mutable_. IPNS isn't fully robust yet, but you can already try it out. check it with both `ipfs name` and with the `/ipns/local/` after `ipfs mount`.

We probably need an example of how to use IPNS.

cc @whyrusleeping

**Comment by rdrey** [comment]
Ah cool, thanks. I'll check it out. :)

**Comment by whyrusleeping** [comment]
I have a little ipns example here: https://github.com/ipfs/examples/tree/master/examples/ipns

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-does-an-ipfs-app-update-itself/296.
