### ISSUE TITLE
Dapps architecture in the near future?

### ISSUE THREAD

**Issue by pavetok** [ipfs/faq#133]
Dapps architecture in the near future?

| Platform | Write data store | Read data store | Data store API |
| --- | --- | --- | --- |
| "plain old" browser | event-log-like (IPFS) | blockchain-like ( IPFS) | HTTP |
| electron app | blockchain-like (IPFS) | key-value-like (IPFS) | JavaScript |
| ipfs browser | key-value-like (IPFS) | sqlite-like | something else? |
| something else? | something else? | pouchdb-like |  |
|  |  | something else? |  |

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/dapps-architecture-in-the-near-future/438
