### ISSUE TITLE
How do I see the logs and change the log levels (go-ipfs)?

### ISSUE THREAD

**Issue by harlantwood** [ipfs/faq#134]
Answer: this works well:

```
IPFS_LOGGING=<level> ipfs daemon
```

...where <level> is the log level, with 'debug' the most verbose and 'critical' the least verbose.  Possible values of <level>: debug, info, notice, warning, error, critical.

Some more useful discussion here: https://github.com/ipfs/go-ipfs/issues/1816.

**Comment by harlantwood** [comment]
in short, this seems to work well:

```
IPFS_LOGGING=<level> ipfs daemon
```

...where \<level\> is the log level, with 'debug' the most verbose and 'critical' the least verbose.  Possible values of \<level\>: debug, info, notice, warning, error, critical.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-do-i-see-the-logs-and-change-the-log-levels-go-ipfs/352
