### ISSUE TITLE
Turn IPFS path into multihashes in one API call?

### ISSUE THREAD

**Issue by matthewrobertbell** [ipfs/faq#135]
If I have /ipfs/(some hash)/a/b/c , is there a way to turn a, b and c into multihashes in one call? This can be done one at a time with calls to object stat, but one call would be nice

**Comment by Kubuxu** [comment]
You can use:

```
 ~  ipfs resolve /ipfs/QmR1AeboA161SNxfSgRYtp264RucPVYcHLradx3kJP2f4o/trooper.jpg             ✘ 
/ipfs/QmY3nJ4zW5j5dJ8LmNT9yF3Twp9dv5FP18rLf5kDXMBhYP
```

It will resolve recursively until single multihash.

**Comment by matthewrobertbell** [comment]
I don't mean a single result, I mean the multihash for every component of the path in one call, A, B and C.

**Comment by Kubuxu** [comment]
Then no, there isn't command like that, you would have to use some script.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/turn-ipfs-path-into-multihashes-in-one-api-call/389.
