### ISSUE TITLE
Installing SSL certificate?

### ISSUE THREAD

**Issue by ghost** [ipfs/faq#136]
Can we install a valid SSL certificate to our gateway/API Server so that we can use https? The http support would still be there but as an option we should be able to install an SSL certificate.

**Comment by Kubuxu** [comment]
We decided not to implement HTTPS into go-ipfs codebase itself. Please use dedicated HTTP(S) front end server for that purpose (nginx or Apache).

**Comment by llopv** [comment]
It would be great to refer here the apache/nginx configuration to do that. Does anybody have it configurated this way?

**Comment by jbenet** [comment]
See the infra repo -- should be there https://github.com/ipfs/infrastructure

**Comment by Kubuxu** [comment]
You can also consider using something like Caddy: https://caddyserver.com/
Warning, I didn't test it.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/installing-ssl-certificate/388.
