### ISSUE TITLE
File System Operations?

### ISSUE THREAD

**Issue by ghost** [ipfs/faq#139]
I see we can add and delete files to/from IPFS. How about other operations, like rename, make dir, remove dir, move, copy, etc? Will there be a Unix like file system tooling in the future?

**Comment by hackergrrl** [comment]
Great question! For exactly this use case IPFS has the Files API. It's still pending some more documentation, but you can explore it with go-ipfs by typing `ipfs files --help`, and can read a bit about it [on this blog post](http://blog.ipfs.io/14-ipfs-0-4-0-released/).

**Comment by ghost** [comment]
Awesome, great to hear this.

**Comment by ghost** [comment]
Ooops, I forgot this was faq. Reopening.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/file-system-operations/272.
