### ISSUE TITLE
Using IPFS for storing data for Blockchain apps. (blockstore, etc)

### ISSUE THREAD

**Issue by jbenet** [ipfs/faq#14]
(This is not quite a F.A.Q. but a discussion rather)
See https://twitter.com/lightcoin/status/590293410768007168

**Comment by prestonjbyrne** [comment]
I think this group also needs a name.

**Comment by muneeb-ali** [comment]
Some background on the data-storage of Blockstore:

https://github.com/openname/blockstore/wiki/Data-Storage

**Comment by jbenet** [comment]
@shea256 @muneeb-ali @compleatang @prestonjbyrne

**Comment by jbenet** [comment]
actually, let's go here: https://github.com/ipfs/blockchain-data/issues

**Comment by jbenet** [comment]
carry over this discussion on: https://github.com/ipfs/blockchain-data/issues tag anyone else in https://github.com/ipfs/blockchain-data/issues/1
