### ISSUE TITLE
Will updating files be reflected to all nodes copied it?

### ISSUE THREAD

**Issue by ghost** [ipfs/faq#140]
If I update a single file, will be updated to its latest version on all nodes in the network that previously copied the updated file?

**Comment by Kubuxu** [comment]
No, if you update the file and add it to IPFS again, it will have different hash. IPFS uses hash as unique identifier of a file.

You can use IPNS system to keep reference to the newest version of given file.

**Comment by ryobg** [comment]
See also #156

**Comment by madavieb** [comment]
This issue was moved to https://discuss.ipfs.io/t/will-updating-files-be-reflected-to-all-nodes-copied-it/291.
