### ISSUE TITLE
A way to get a list of peers using my service

### ISSUE THREAD

**Issue by mitar** [ipfs/faq#144]
Based on [Making your own ipfs service](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/api/service/readme.md), it seems there is no way to ask IPFS for peer IDs of everyone (or at least X number of random) using my service? How can I then bootstrap my service? It would be great if I could say: tell me at least X number of other peers using my service. And then I could communicate with them.

**Comment by ghost** [comment]
There's not really any service discovery in IPFS yet -- we have a few early ideas here: https://github.com/ipfs/notes/issues/15

**Comment by mitar** [comment]
I am currently using pubsub feature to get peers of everyone subscribed to a topic used by my service.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/a-way-to-get-a-list-of-peers-using-my-service/470
