### ISSUE TITLE
What do Node Start and Node Stop mean in the API Spec?

### ISSUE THREAD

**Issue by whereswaldon** [ipfs/faq#145]
On [the API spec](https://github.com/ipfs/specs/tree/1a17d32426f907fb125795e88aca5fa6003f642c/api/core) there are two commands listed under `node` called `start` and `stop`. However, they are not listed anywhere in [this API reference](http://docs.ipfs.apiary.io/#reference/id/get). Where and how are those commands defined?

**Comment by alugarius** [comment]
This commands are not in the go-ipfs help too!

**Comment by whyrusleeping** [comment]
Those commands havent actually been accepted as part of the api. I'm not really sure what that document is for, @diasdavid any insight?

**Comment by daviddias** [comment]
That list was written down by me, @jbenet and @dignifiedquire during a convo to get documented what are the Core API calls of IPFS, a long time ago. js-ipfs has them, however that spec is a work in progress.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-do-node-start-and-node-stop-mean-in-the-api-spec/330.
