### ISSUE TITLE
How would IPFS be implemented in browser?

### ISSUE THREAD

**Issue by alcinnz** [ipfs/faq#147]
I get that IPFS supports WebRTC specifically so it can be implemented within a browser tab, ipfs-js is developed specifically to get to that point, and Juan Benet talks about how this is part of the adoption plan for IPFS. And this is important because without it IPFS would face no more adoption than Freenet or Tor Hidden Services do (despite offering more). 

I can see how the protocol could be implemented in the browser (after all JavaScript is Turing complete and now has LocalStorage for persistence and WebRTC for peer-to-peer networking). And a cache manifest could help keep this complex JavaScript cached on the client-side.

What I don't get is how would you display IPFS hosted pages such that you can intercept all their requests to be potentially handled by that protocol implementation. Can you convince me that you have plans to make this work?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-would-ipfs-be-implemented-in-browser/319
