### ISSUE TITLE
Does IPFS support git merge strategies?

### ISSUE THREAD

**Issue by EtherTyper** [ipfs/faq#151]
IPFS uses git to version files. Does this mean it supports using git's complex merge strategies like recursive and octopus to track files?

**Comment by EtherTyper** [comment]
I believe someone can at @ipfs can mark this as answered by #156.

**Comment by RichardLitt** [comment]
Should we close this as a dupe?

**Comment by EtherTyper** [comment]
@RichardLitt Probably not. We should keep it for clarification, I think.

**Comment by RichardLitt** [comment]
Sounds good. Decided to keep it, too (deleted a comment asking we should delete it as a dupe, before the response, for anyone who is curious about the information flow.)

**Comment by llopv** [comment]
The question is not responded in the issue refered above.

According to the IPFS paper:

*The full power of the Git version control tools is available to IPFS users. The object model is compatible, though not the same. It is possible to (a) build a version of the Git tools modified to use the IPFS object graph, (b) build a mounted FUSE filesystem that mounts an IPFS tree as a Git repo, translating Git filesystem read/writes to the IPFS formats.*

**Comment by EtherTyper** [comment]
@llopv Yes it is. The following reiterates on object immutability in IPFS, which means that objects cannot have differentials or be merged together natively.

> ... in effect objects added to ipfs cannot be deleted or edited. If an edit is required the file(s) must be edited locally and re-uploaded to ipfs, generating a new hash value for the file(s). ...

**Comment by EtherTyper** [comment]
@llopv Though it is weird the issue contradicts the whitepaper...

**Comment by jbenet** [comment]
> The following reiterates on object immutability in IPFS, which means that objects cannot have differentials or be merged together natively.

What do you mean? Yes they can be-- this is exactly how git works. In git, all objects are immutable, and you use _names_ (branches) to point to the latest immutable object. this is a hash-chain, merkle-dag or whatever you want to call it.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-support-git-merge-strategies/274
