### ISSUE TITLE
 Edit New issue Does ipfs use a blockchain 

### ISSUE THREAD

**Issue by aronayne** [ipfs/faq#152]
Re-posting question as per recommendation from here https://github.com/ipfs/go-ipfs/issues/3004#issuecomment-235978847

From reading the ipfs whitepaper : https://github.com/ipfs/papers/raw/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf ipfs does not appear to make use of the blockchain.

Blockchain is referenced in the doc here :

This forms a generalized Merkle
DAG, a data structure upon which one can build versioned
file systems, blockchains, and even a Permanent Web.

and here :

A raw data field and a common link structure are the
necessary components for constructing arbitrary data structures
on top of IPFS. While it is easy to see how the Git
object model fits on top of this DAG, consider these other
potential data structures: (a) key-value stores (b) traditional
relational databases (c) Linked Data triple stores (d)
linked document publishing systems (e) linked communications
platforms (f) cryptocurrency blockchains.

My understanding before I investigated myself is that ipfs utilised a blockchain and formed the assumption that ipfs stored data in blocks, that perhaps were pre-mined. But it seems this assumption is incorrect ? If ipfs does not currently utilise a blockchain are there plans for ipfs to incorporate a blockchain ?

**Comment by RichardLitt** [comment]
Thanks for reopening, @adrian-git-hub-user.

As I said in the other issue: no, IPFS does not use a blockchain. This is stated in the quotes you mention, too. You can build a blockchain on top of IPFS.

> My understanding before I investigated myself is that ipfs utilised a blockchain and formed the assumption that ipfs stored data in blocks, that perhaps were pre-mined. But it seems this assumption is incorrect? 

Yep, that's not right. Not sure where you got that assumption. 

> If ipfs does not currently utilise a blockchain are there plans for ipfs to incorporate a blockchain ?

Sure. Take a look at [these issues](https://github.com/ipfs/faq/search?utf8=%E2%9C%93&q=blockchain). I would also check out [the Filecoin paper](http://filecoin.io/filecoin.pdf).

**Comment by ghost** [comment]
@adrian-git-hub-user see also [eris-ltd/eris-cli](https://github.com/eris-ltd/eris-cli), it is a tool to build and use blockchains, you could store data or other contracts on them. also it gives you an interface to ipfs
