### ISSUE TITLE
Is there any way to check the "health" of an ipfs file?

### ISSUE THREAD

**Issue by traverseda** [ipfs/faq#153]
With torrents, you can generally get the number of seeders. Does ipfs have a similar mechanism? Can ipfs have a similar mechanism?

**Comment by RichardLitt** [comment]
Currently, it looks like you can only get a lower bound: `ipfs dht findprovs <hash> | wc -l`. For example:

```
$ ipfs dht findprovs QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ | wc -l
20
```

**Comment by traverseda** [comment]
And what, exactly, does that do?

What's a prov?

**Comment by RichardLitt** [comment]
A provider, here represented by the peer ID, is a peer in the DHT that can provide a specific value, given a key. In essence, AFAIK, a seeder. So, there are 20 seeders for that hash.

**Comment by Ghoughpteighbteau** [comment]
http://ipfs.io/ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ/cat.jpg

why do so many people have this picture :laughing:

**Comment by Kubuxu** [comment]
Because people love kittens.

**Comment by EtherTyper** [comment]
@Ghoughpteighbteau It's a picture used in some IPFS tutorials.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/is-there-any-way-to-check-the-health-of-an-ipfs-file/338.

**Comment by shessenauer** [comment]
Is dht findprovs available with ipfsjs? Getting promise errors when trying to implement (Not from my end)
