### ISSUE TITLE
What is pubsub?

### ISSUE THREAD

**Issue by thisconnect** [ipfs/faq#157]
In some places there are mentions that pubsub will be implemented into IPFS. 

Does that mean one can subscribe to a node and listen for dynamic data?

**Comment by RichardLitt** [comment]
This repository, https://github.com/libp2p/pubsub, might be helpful.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/what-is-pubsub/332
