### ISSUE TITLE
Vanity generator for public key hashes?

### ISSUE THREAD

**Issue by mateon1** [ipfs/faq#158]
I'm interested whether there exists a vanity hash generator for IPFS public/private keypairs, similar to Bitcoin or other cryptocurrencies.
An example: `findvanity QmIPFS` -> `QmIPFSistvz5r37jedMyXsTZ7i8AtrcpZJavoU8Jn7Ysju; keypair: [public key and private key]`

**Comment by Kubuxu** [comment]
It will be currently really slow as we use RSA 2048 right now.

In not a far future we plan moving to ed25519 in which case you can easily reach up to 17 generated keys per second.

**Comment by mateon1** [comment]
Hm, in that case, how were `QmSoL` nodes created? Are they running a modified version of IPFS where the peer ID doesn't represent the pubkey?

**Comment by Kubuxu** [comment]
No, it was just slow.

Something like that wouldn't be possible as your node would refuse to connect to them.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/vanity-generator-for-public-key-hashes/283.
