### ISSUE TITLE
IPFS / IPLD Diff Merge?

### ISSUE THREAD

**Issue by matthewrobertbell** [ipfs/faq#159]
If a single block in a 1GB file is changed, to update, a node only needs to re-download one small block, which is fine.

If a few bytes are added to the start of the file, or if a bunch of small changes are made, is this currently inefficient?

If so, is the support of diff objects planned? For example: ipfs_object_hash_1 + ipfs_diff_object_hash -> ipfs_object_hash_2

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-ipld-diff-merge/432
