### ISSUE TITLE
Pin tutorial on ipfs.io

### ISSUE THREAD

**Issue by kevinsimper** [ipfs/faq#160]
I wondered a lot why there were no articles about distributing files with ipfs hence the whole websites talks about in abstract.

I imagine that it is pretty difficult for newcomers to come all the way to this git repo 😄 

Could there be an article about "pinning" be added that don't have pinning as the headline? Then I think more people would understand IPFS, since without pinning the file really only exist on one machine.

I know this article, but as I am totally new to IPFS, this article does not really help me with my problem. How do I distribute a 5 GB video file, so it is not only on my machine?

https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/pinning/readme.md

Btw. ipfs is awesome, now just 20 minutes into it!

**Comment by kevinsimper** [comment]
I now read a lot more about it and even tried `ipfs files`, `ipfs mount` and it is still totally awesome, but I also understand that it is not as simple as to just synchronize two folders!

But maybe it should just say that: it is not easy synchronizing folders! ;)

**Comment by whyrusleeping** [comment]
Hey @kevinsimper, glad to hear youre enjoying ipfs :)

Some reading that might help here:
- https://github.com/ipfs/faq/issues/8
- https://github.com/ipfs/faq/issues/47

**Comment by RichardLitt** [comment]
@kevinsimper We're working on exactly this, too - making tutorials that explain pinning. We'll update when we have some. cc @flyingzumwalt

**Comment by flyingzumwalt** [comment]
Yeah. #47 is the best explanation at the moment, though it rambles a bit and has a confusing title.  I'm working on a new set of tutorials that will cover pinning as part of the [Files on IPFS](https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/files-on-ipfs/) tutorial but, alas, at the moment it's [just stubbed out](https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/files-on-ipfs/lessons/3-pin-files.html) I will be filling in all of these lessons over the coming weeks.

**Comment by flyingzumwalt** [comment]
I've created a ticket to track this work so you can follow along. See ipfs/community#163 and the [associated milestone](https://github.com/ipfs/community/milestone/1)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/pin-tutorial-on-ipfs-io/403.
