### ISSUE TITLE
What is the recommended way to run multiple nodes on the same server?

### ISSUE THREAD

**Issue by gbolo** [ipfs/faq#162]
ipfs expects it's config file in $HOME/.ipfs/config, unless IPFS_PATH is set,  then it looks at $IPFS_PATH/config

For multiple deamons just set a different IPFS_PATH for each and make sure that their listener addresses (and ports) defined in the config do not overlap .

**Comment by Kubuxu** [comment]
We leave issues open in this repo, and just mark is as answered.

Thanks for applying WTFM approach for your question.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/what-is-the-recommended-way-to-run-multiple-nodes-on-the-same-server/464
