### ISSUE TITLE
Change repo license?

### ISSUE THREAD

**Issue by davelab6** [ipfs/faq#165]
The README is licensed under CC-BY-NC-SA, but this prevents it from being remixed for other projects that have commercial development, which is almost all libre software projects. 

Would you be willing to change to CC-BY-SA (same as wikipedia) such that other libre software projects can use this? :)

**Comment by jbenet** [comment]
I'd be ok with that-- others in the community?

**Comment by RichardLitt** [comment]
Works for me!

**Comment by davelab6** [comment]
Any other rightsholders? :)

**Comment by RichardLitt** [comment]
@flyingzumwalt Might have some thoughts.

**Comment by flyingzumwalt** [comment]
👍

**Comment by davelab6** [comment]
Per https://github.com/ipfs/faq/graphs/contributors @RichardLitt and @jbenet are the only rightholders for the README file, which is the work I'm enquiring about :)
