### ISSUE TITLE
Does IPFS allow for encrypted blocks?

### ISSUE THREAD

**Issue by cyisfor** [ipfs/faq#168]
I'm pretty sure IPFS doesn't encrypt anything, but I want to make sure. An IPFS hash is _just_ a content hash, right? There's no encryption key added as a suffix to the URI, or anything? I ask because it's important to know, for anyone wanting to implement a system over IPFS that in any way automatically relays or replicates content from others. If IPFS URIs have no spot for a decryption key, then the implementers would have to write their own on top of IPFS, otherwise anyone who used their system could get well... jailed, if someone ever injects illegal data into their network.

I like the idea of automatic relays, so that I can subscribe to things that can download new stuff on demand, such as discussion forums. But I'm pretty sure nothing like that can exist in IPFS's current state, unless a custom layer of encryption is written?

**Comment by jbenet** [comment]
- block level encryption is planned
- ipfs nodes do not download content automatically, they have to be told to
- protocols like what you describe (automatic relays) are planned and will
  be completely opt in.

These questions have been asked before. You may find more in depth answers
searching around.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-allow-for-encrypted-blocks/362
