### ISSUE TITLE
editing/deletion of content by another PC

### ISSUE THREAD

**Issue by cheershendtco** [ipfs/faq#169]
https://github.com/ipfs/faq/issues/156

> So in effect objects added to ipfs cannot be deleted or edited. If an edit is required the file(s) must be edited locally and re-uploaded to ipfs, generating a new hash value for the file(s).

If I have uploaded files with my PC, and how to manager these files with other PCs?
Thanks

**Comment by Voker57** [comment]
```
ipfs get <hash>
# edit the directory
ipfs add <directory>
```

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/editing-deletion-of-content-by-another-pc/436
