### ISSUE TITLE
Why is the address /ipfs/QmQmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn so common?

### ISSUE THREAD

**Issue by JesseWeinstein** [ipfs/faq#173]
Because it is the address for the empty directory. So every time an empty directory is referred to, that will be the address given for it. It is also the default value that a peer publishes on IPNS, so you'll see it there a lot too.

**Comment by JesseWeinstein** [comment]
You can verify this as follows:

```
mkdir an_empty_directory ; ipfs add -r an_empty_directory/
```

which will output:

```
added QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn an_empty_directory
 0 B / 4.00 KB [-------------------------------------------------------------------------------------------------------------------------------------]   0.00%
```

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/why-is-the-address-ipfs-qm-so-common/493
