### ISSUE TITLE
Get File meta data

### ISSUE THREAD

**Issue by jonmyates** [ipfs/faq#174]
Hello,

Having 'add'ed a file (an image of type jpg) using the add command, I'm struggling to find the command to get the meta data about it (name, IPFS location, etc).

When I perform either a GET <hash> or a CAT <hash> I just get the text version of the file back.

Ideally, having listed my files I'd like to get some data in them.

I'm using and API client (POSTMAN) to send the requests.

Can anyone please advise?

**Comment by kevinsimper** [comment]
I asked a similar question, you can see it here :) https://github.com/ipfs/faq/issues/163

**Comment by jonmyates** [comment]
Thanks Kevin. 

So to get the meta-data on a file, the containing folder needs to be added?

Cheers. 

Jon

**Comment by kevinsimper** [comment]
@jonmyates Yes, you are right! 👍

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/get-file-meta-data/329.
