### ISSUE TITLE
faq tweaks?

### ISSUE THREAD

**Issue by mcast** [ipfs/faq#175]
I like ipfs/faq, it's a neat hack!  Also thanks for the meta label (which I can't apply myself).

First I set off to turn the whole FAQ "purple", but of course GitHub doesn't do purple links.  Then I had other ideas...
- encourage readers to +1 on the top (question) post on their favourite few; noting that these (in current GitHub UI) seem to be lightweight ~~but irrevocable~~.
- use either milestones or another label or two, to collect "the best"
- suggest a consensus mechanism for extracting the essence of questions into a new issue, if they get long & off topic?  Not sure what.

I'm guessing that questions are on a frequency scale, and many people don't need to read out to the end of the long tail / just want to hear the obvious.

**Edit:** cancel your "reaction" by clicking it, it has a pale blue background.

**Comment by mcast** [comment]
(thanks)

"Milestones ... to collect the best", rather several to make topic headings?
- Basics
- Updating
- Legal
- Anonymity
- ... I haven't read enough of them to make a good set of headings.

Milestones:issues = 1:many works like headings:questions.  However I see that some issues cut across multiple topics already.  Ordering of the topics might help?

Labels:issues being many:many might work better, for an interactive FAQ presentation?

**Comment by RichardLitt** [comment]
> encourage readers to +1 on the top (question) post on their favourite few; noting that these (in current GitHub UI) seem to be lightweight but irrevocable.

SGTM. They are revocable; I don't think you can sort by these, though, sadly. Let's add a line to the README encouraging them. 

> use either milestones or another label or two, to collect "the best"

I think many labels makes more sense. Many to many makes more sense. 

> suggest a consensus mechanism for extracting the essence of questions into a new issue, if they get long & off topic? Not sure what.

This is hard; people will always go off topic. I don't want to close or lock topics, either. I think the way we've been doing it is OK. I don't mind redirecting people, or telling them something is off topic.

**Comment by mcast** [comment]
> > ... extracting the essence of questions into a new issue, if they get long & off topic? Not sure what.
> 
> This is hard; people will always go off topic. I don't want to close or lock topics, either. I think the way we've been doing it is OK. I don't mind redirecting people, or telling them something is off topic. 

At this point I was referring to the future "will be rendered" #55.  The way issues progress is good.

**Comment by jbenet** [comment]
Whatever is most useful to the community. Definitely can have improvements.
But we can also add too many features (making it a bit confusing too). I
think @RichardLitt and @flyingzumwalt will have a ton of good thoughts on
what to do

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/faq-tweaks/316.
