### ISSUE TITLE
Add using C#

### ISSUE THREAD

**Issue by jonmyates** [ipfs/faq#178]
Hello,

Would anyone please be able to advise how to add a file using C#?

I have the Get working:

```
var myRequest = WebRequest.CreateHttp("http://127.0.0.1:5001/api/v0/object/get?arg=QmNkxQz8JzmK6Y2VUdJ8K8gVx2jrhhzLc7ESsfjnKw8coK");
            myRequest.Method = "GET";
            myRequest.UserAgent = "WebRequestDemo";

            using (var theResponse = myRequest.GetResponse())
            {
                var dataStream = theResponse.GetResponseStream();
                StreamReader reader = new StreamReader(dataStream);
                object objResponse = reader.ReadToEnd();
                dataStream.Close();
                theResponse.Close();
            }
```

But can't seem to workout the Add.

Thank you.

J

**Comment by RichardLitt** [comment]
I'm not sure. This may belong in [ipfs/support](//github.com/ipfs/support).

**Comment by richardschneider** [comment]
You must POST a multipart/form-data to the IPFS server.

Here's an [example](https://github.com/richardschneider/net-ipfs-api/blob/master/src/Add.cs) using `HttpClient`.  Feel free to either copy the code or use the [Ipfs.Api](https://github.com/richardschneider/net-ipfs-api).

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/add-using-c/266.
