### ISSUE TITLE
Is the js-ipfs Javascript library the equivalent for IPFS of what WebTorrent is to Bittorrent?

### ISSUE THREAD

**Issue by mayerwin** [ipfs/faq#180]
Is the browser-embeddable Javascript library [js-ipfs](https://github.com/ipfs/js-ipfs) the equivalent for IPFS of what [WebTorrent](https://webtorrent.io/) is to Bittorrent? How does fallback work for browsers that do not support WebRTC?

**Comment by daviddias** [comment]
Hi @mayerwin, apologies for taking so long to get back to you, I completely missed this one.

`js-ipfs` is a full node, not a light client. In its final state it will be able to talk with any node in the network. See a more complete answer here: https://github.com/ipfs/faq/issues/97

**Comment by mayerwin** [comment]
@diasdavid Thanks, I didn't find the answers to the second part of the question though: does js-ipfs make use of WebRTC? If so, is there any fallback to browsers that do not support it to ensure js-ipfs works on all major browsers (Firefox, Chrome, Edge, Safari)?

**Comment by daviddias** [comment]
@mayerwin right! On that part, the simple answer is Yes and Yes 🌐, IPFS uses libp2p, a modular network stack that enables IPFS to use transports like: WebRTC, WebSockets, HTTP, uTP, TCP and QUIC to name a few. However, if no WebRTC is available, it means that the other transport used (namely for the browser it will have to be WebSockets or HTTP), will need to be 'upgraded' to be able to do things like Relay/TURN, but that is also part of the libp2p modular stack. See more here: https://github.com/libp2p/js-libp2p

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/is-the-js-ipfs-javascript-library-the-equivalent-for-ipfs-of-what-webtorrent-is-to-bittorrent/281.
