### ISSUE TITLE
How is keys stored in the dht?

### ISSUE THREAD

**Issue by kevinsimper** [ipfs/faq#182]
I read the IPFS design paper and I did not understand, how are keys stored in the dht?
Do the keys only get stored on your own nodes or does it get put to other nodes, so they know I have it?

If they are stored on other nodes, how do I access what routing info that I store about other nodes?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-is-keys-stored-in-the-dht/349
