### ISSUE TITLE
What exactly happens if we run out of hashes?

### ISSUE THREAD

**Issue by alugarius** [ipfs/faq#183]
I heard of Multi-hash and saw some github repos that suggest IPFS is future proof.
"It is useful to write applications that future-proof their use of hashes" --https://github.com/multiformats/multihash/blob/master/README.md

That one day, in billions of years if we got more than 46^62 files, what exactly happens?

**Comment by RichardLitt** [comment]
Thank you, @alugarius! Someone pointed out that #24 was closed and very similar. Closing this in favor of that, and reopening it. 

But it's great you made this, the wording above is unique and will point people to #24. Thank you!

**Comment by Kubuxu** [comment]
The `46^62 = 1.23 * 10^103` is bigger than number of atoms in the universe which is estimated to be `10^80` [1].

[1]: https://en.wikipedia.org/wiki/Observable_universe#Matter_content_.E2.80.93_number_of_atoms

**Comment by alugarius** [comment]
@Kubuxu that does not matter to me or has to do with my question. ...
but thanks for the fun-fact...

I guess...

**Comment by Kubuxu** [comment]
It means that even if you were able to store a file in every atom of the universe you would still have a lot of hashes left.

**Comment by Ghoughpteighbteau** [comment]
also I think the multihash format would support adding an extra bit or two. You know, just in case you wanted to support another universe.

**Comment by alugarius** [comment]
@Ghoughpteighbteau That sound good
