### ISSUE TITLE
IPFS monitoring options

### ISSUE THREAD

**Issue by aronayne** [ipfs/faq#187]
Using the webui https://github.com/ipfs/webui seems using the webui can the following be accessed :
- the number of connected nodes ?
- the hash values stored on each node ?
- IP address of machine participating in network ?

And/or can this data be access via the IPFS cli ?

**Comment by Kubuxu** [comment]
Yes:
- number of connected nodes: `ipfs swarm peers | wc -l`
- I don't know right now.
- check `ipfs id`

**Comment by ghost** [comment]
You can also query http://localhost:5001/debug/metrics/prometheus to get more runtime metrics

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-monitoring-options/431
