### ISSUE TITLE
How should I configure my firewall?

### ISSUE THREAD

**Issue by insanity54** [ipfs/faq#19]
Foreword: I'm not actually in need of an answer, I'm just trying to help out by populating the FAQ from questions I see on freenode #ipfs

[Q](https://botbot.me/freenode/ipfs/2015-04-28/?msg=37750807&page=4): Is there is anything I should know about firewall configuration to get ipfs running?
[A](https://botbot.me/freenode/ipfs/2015-04-28/?msg=37750865&page=4): The best thing for your firewall is to forward port 4001

**Comment by whyrusleeping** [comment]
Port 4001 is what is known as the "swarm address", this is configurable in your `.ipfs/config` file.

**Comment by dylanPowers** [comment]
An alternative answer is to make sure UPnP is running correctly on your router, then the port forwarding will be correctly configured automatically.

**Comment by ThomasWaldmann** [comment]
@dylanPowers having uPnP active is considered a security risk by many people. So while it is "plug and play" (and thus easier / more comfortable), malware could use it to open additional ports for itself (or maybe reconfigure your router otherwise).

**Comment by cryptix** [comment]
I'm with Thomas on this one, there were also cases of plastic home routers answering upnp requests on the outside WAN (netgear for instance IIRC). If we advise to do this we need a big warning sign, imho.

**Comment by ghost** [comment]
Please let me ask a newbie question: Which protocol do we need to allow in our firewall/NAT configurations for the port 4001? TCP, UDP or both?

**Comment by insanity54** [comment]
@David-Leudolph Just TCP I believe. That's how I have mine configured, and the outside world can access the files I have added to IPFS.

**Comment by mitar** [comment]
But if upnp is supported, then mentioning this should be in FAQ.

**Comment by pyhedgehog** [comment]
How should it be configured if I have several ipfs nodes behind same firewall?

**Comment by xloem** [comment]
@pyhedgehog you should edit your .ipfs/config file for each node to give it a different swarm port from the others, and forward that port to that box in your firewall.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-should-i-configure-my-firewall/471.
