### ISSUE TITLE
Where does IPFS store data on a Windows system?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/faq#191]
By default, in `%USERPROFILE%/.ipfs` (on Win 7/8/10 that's `C:\Users\<username>\.ipfs`).

**Comment by ntninja** [comment]
May I ask why `%LOCALAPPDATA%\IPFS` isn't used instead?
It seems the me that the raw IPFS block cache, logs and network configuration isn't something that will interest many users a lot‽ We throw it right into their home directories, then?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/where-does-ipfs-store-data-on-a-windows-system/310
