### ISSUE TITLE
How can IPFS deal with the latest version of a datum?

### ISSUE THREAD

**Issue by piotr-yuxuan** [ipfs/faq#192]
First, thank you for IPFS, it seems to be a definitely fun and perhaps promising idea :-)

Any document is dynamic most of the time: its URL can change and so can its content itself. IPFS hashes solves the first part but how can we retrieve the latest available version of a document?

To the best of my knowledge, tree-based version control system (such as git) makes it trivial to access to parents of a document but further revisions are less easily accessible.

**Comment by leroycep** [comment]
The IPNS (InterPlanetary Name Space) solves the issue of accessing the latest document. It is described near the end of the [IPFS white paper](https://github.com/ipfs/papers/raw/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf).

Every user is assigned a namespace at `/ipns/<NodeId>`. Then a user can put new files at places underneath this, like `/ipns/<NodeId>/cat.gif`, which would link to a IPFS content address in its metadata.

**Comment by fasiha** [comment]
Here’s a tidy summary how people accomplish this: https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/ 😊

**Comment by piotr-yuxuan** [comment]
Great thank you for your explanations, I can close it.

**Comment by RichardLitt** [comment]
Let's keep this open to make it more easily searchable. Adding the answered label. :)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-can-ipfs-deal-with-the-latest-version-of-a-datum/305.
