### ISSUE TITLE
Does IPFS use proof-of-work?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#193]
The IPFS whitepaper (draft 3) states for S/Kademlia:

> One scheme includes a proof-of-work crypto puzzle to make generating Sybills expensive.

Generating an IPFS identity is very fast on my computer and I don't see any code pointing to proof-of-work. Does IPFS use (or plan to use) proof-of-work to fight Sybills?

**Comment by whyrusleeping** [comment]
We have thought about it, And if we need to do this to prevent sybills, we will very likely implement it.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-use-proof-of-work/315
