### ISSUE TITLE
What are the benefits of persisting identity?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#195]
The IPFS whitepaper states

> Users are free to instatiate a “new” node identity on every launch, though that loses accrued network benefits. Nodes are incentivized to remain the same.

What are the incentives for nodes to keep their identity?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/what-are-the-benefits-of-persisting-identity/303
