### ISSUE TITLE
Is the IPFS white paper on GitHub?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#196]
I had a quick look and couldn't find it. There a small typo ("regualarly") I wanted to report.

**Comment by RichardLitt** [comment]
Yes, it is. 

https://github.com/ipfs/papers

**Comment by JustinDrake** [comment]
Cool. For future reference the file is https://github.com/ipfs/papers/blob/master/ipfs-cap2pfs/ipfs-cap2pfs.tex

**Comment by RichardLitt** [comment]
Thanks @JustinDrake. Keeping this open in case other people search for it later!

**Comment by RichardLitt** [comment]
And here, in case you want the PDFs: https://github.com/ipfs/papers/blob/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/is-the-ipfs-white-paper-on-github/326.
