### ISSUE TITLE
Do IPFS nodes have a user agent string?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#198]
I have written an IPFS crawler that finds about 200 IPFS online nodes. I was curious to know how many of those are `go-ipfs` and how many are `js-ipfs`. Is there a user agent string I can query to get that sort of statistic?

**Comment by ghost** [comment]
You can connect to the respective node and make use of the `/ipfs/id/1.0.0` protocol on top of the swarm: https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go

**Comment by duomoney** [comment]
I found out that the id protocol gives out very little information. There's an agent version, and protocol version. The agent version is either `0.1.0` or `3.3.4`. The protocol version is always `0.1.0`. This is in contrast to the many [go-ipfs versions](https://dist.ipfs.io/go-ipfs/versions) shipped in the past.

Is there a way to get the go-ipfs version?

	"AgentVersion": "go-libp2p/3.3.4",
	"ProtocolVersion": "ipfs/0.1.0"

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/do-ipfs-nodes-have-a-user-agent-string/381.
