### ISSUE TITLE
How do go-ipfs and js-ipfs compare?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#199]
I'm curious to get a feel for how `go-ipfs` and `js-ipfs` compare. Below are specific questions:

1. How many people are working on the respective implementations?
2. How old are the two implementations?
3. Which implementation is most stable (e.g. most tested)?
4. Which implementation is mostly used in production?
5. How does performance compare across the two implementations?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-do-go-ipfs-and-js-ipfs-compare/302
