### ISSUE TITLE
Are there restrictions for the name of IPFS links?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#201]
In the whitepaper, an `IPFSLink` is defined as

```
type IPFSLink struct {
  Name string
  Hash Multihash
  Size int
}
```

The paper then allows for content addressing using the name. It is noted that paths work like in traditional UNIX filesystems and the Web.

<img width="559" alt="screen shot 2016-11-23 at 14 11 38" src="https://cloud.githubusercontent.com/assets/731743/20564894/13b7e0c4-b187-11e6-8b89-b5054cca8310.png">

Can `Name` be an arbitrary string, with characters such as whitespace or `/`, or any character disallowed in web URIs? Does the protocol require that `Name` be sanitised so that OSes/filesystems/applications can safely parse name paths?

**Comment by ghost** [comment]
I'm not sure there are *any* restrictions right now. If a link name contains a forward-slash, you just won't be able to address it through the standard ipfs tools (cli, gateway, fuse). There's a lengthy interesting discussion in ipfs/go-ipfs#1710.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/are-there-restrictions-for-the-name-of-ipfs-links/260
