### ISSUE TITLE
Can two peers without a common transport communicate?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#202]
Let's assume we have two IPFS peers `A` and `B` without a common transport. For example, `A` is a `go-libp2p` node which supports TCP and WS, whereas `B` is a `js-libp2p` node which supports WebRTC. Can `A` and `B` communicate with each other?

One obvious idea is to use a relay node `C` which supports both TCP and WebRTC, and can relay traffic as follows:

           TCP         WebRTC
    A <---------> C <---------> B

Do such relay nodes exist? How would `A` and `B` communicate with each other today?

**Comment by daviddias** [comment]
@JustinDrake we are working on that `TURN` feature, there is code for it already, just not merged into master, it is one of our Q4 goals, so expect news soon :)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/can-two-peers-without-a-common-transport-communicate/282
