### ISSUE TITLE
Have I broken the law if I add an mp3 to IPFS and someone discovers its hash and downloads it?

### ISSUE THREAD

**Issue by slrslr** [ipfs/faq#203]
mp3 or other media where i am not a copyright holder

**Comment by ghost** [comment]
Depending on the jurisdiction you're in: yes, probably. We ask you to not use IPFS for activities that might be illegal.

Please also check out the IPFS community's [Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md#copyright-violations)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/have-i-broken-the-law-if-i-add-an-mp3-to-ipfs-and-someone-discovers-its-hash-and-downloads-it/327
