### ISSUE TITLE
List of IPFS protocols

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#204]
Did I miss anything?

**Current**

`/ipfs/kad/1.0.0`
`/ipfs/relay/line/0.1.0`
`/ipfs/id/1.0.0`
`/ipfs/ping/1.0.0`
`/ipfs/bitswap/1.1.0`
`/ipfs/diag/net/1.0.0`
`/floodsub/1.0.0`

**Legacy**

`/ipfs/dht`
`/ipfs/diagnostics`
`/ipfs/bitswap`
`/ipfs/bitswap/1.0.0`

**Other**

`/echo/1.0.0` (example)
`/p2p/_testing` (testing)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/list-of-ipfs-protocols/345
