### ISSUE TITLE
Traceroute like tool

### ISSUE THREAD

**Issue by theobat** [ipfs/faq#205]
Is there any existing tool for ipfs to show a geophysical trace of the exchanges taking place on an ipfs get ? I'd be really curious to see that... Would it be possible to adapt traceroute to [multiaddress](http://github.com/multiformats/multiaddr) ? Has anyone tried something similar if it does not exist ?

**Comment by theobat** [comment]
Sounds like this could be a good os project :)

**Comment by RichardLitt** [comment]
I'm not sure. Might be a good idea to throw this idea into ipfs/notes; that's a great place to suggest possibilities for new projects on IPFS.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/traceroute-like-tool/322.
