### ISSUE TITLE
Does IPFS use bittorrent or bitswap?

### ISSUE THREAD

**Issue by iskradelta** [ipfs/faq#206]
Or bitswap and bittorrent?

What is bitswap, how does it deal with free-riders/leechers in the swarm?

**Comment by jackie-scholl** [comment]
IPFS uses Bitswap. It does not use Bittorrent in any way. Any references you see to Bittorrent are likely from people trying to explain the similarity, as Bitswap is similar in many ways to Bittorrent. You can learn more about Bitswap by reading this paper: https://github.com/ipfs/papers/blob/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf. Section 3.6 explains Bitswap.

Bitswap does not set one true way of dealing with leeches; instead, it allows clients to set their own *Bitswap strategies*. A Bitswap strategy tells a node how it should request and send blocks to/from its peers. In the paper, they discuss one possible strategy, which uses a "sigmoid scaled by a debt ratio." I don't understand the math involved, but basically it should elegantly handle free-riders and the retention of rare blocks and so on.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-use-bittorrent-or-bitswap/277
