### ISSUE TITLE
Filecoin on ethereum

### ISSUE THREAD

**Issue by dryajov** [ipfs/faq#207]
It was announced no so long ago that filecoin will be implemented on top of ethereum. Is there a high level overview of how it's planed to be done and how it compares to the technique described in the old filecoin withe paper?

**Comment by jbenet** [comment]
@dryajov sorry, this is an IPFS forum. not a Filecoin one. Filecoin announcements will be made in the future, answering this and many other FAQs. thanks for the interest.

**Comment by Methodise** [comment]
A lot of confusion surrounding the filecoin / IPFS relationship. SIA have the best solution. http://sia.tech

**Comment by ghost** [comment]
@Methodise stop the spammy behaviour here and in ipfs/support#36. This is the first warning. See https://github.com/ipfs/community/blob/master/code-of-conduct.md#friendly-harassment-free-space
