### ISSUE TITLE
How does IPNS interact with the DHT?

### ISSUE THREAD

**Issue by jackie-scholl** [ipfs/faq#209]
It's my understanding that you can use IPNS to publish a mutable value linked to your public key, e.g. with https://github.com/whyrusleeping/ipns-pub or the standard cli client. I believe that this key/value pair is distributed directly on the DHT. However, I've also seen some references to this pair only being available for 12 or 24 hours after your node was last online. This doesn't mesh with my understanding of how DHTs work, where every single key/value pair on the network will be stored by multiple nodes (based on the key's closeness to the node ID). It also really doesn't seem to mesh with the stated goals of a permanent web, where content should be available long after the site layout has changed and/or the servers are offline. I've also seen a couple references to some IPRS project in the works that's supposed to help with this, but I'm not sure what that is.

**Comment by jackie-scholl** [comment]
Ok so it looks like the DHT that IPFS is basically a standard DHT, but the DHT clients will drop key-value pairs that are 12-48 hours old (I guess depending on implementation?) and that's why you have to keep re-publishing IPNS messages. My guess is that the same mechanism handles messages from nodes saying they have a certain block.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-does-ipns-interact-with-the-dht/262
