### ISSUE TITLE
How to set ipfs local dir?

### ISSUE THREAD

**Issue by cxgreat2014** [ipfs/faq#210]
I find that ipfs default data path in windows is in `%USERPROFILE%/.ipfs`, how to change it to other place? thanks.

**Comment by Kubuxu** [comment]
It is controlled by environment variable `IPFS_PATH`

See help notes of `ipfs init --help`.

**Comment by cxgreat2014** [comment]
Thanks a lot~！

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-to-set-ipfs-local-dir/391.
