### ISSUE TITLE
how to add some file to a hash folder fast?

### ISSUE THREAD

**Issue by cxgreat2014** [ipfs/faq#211]
I had used  `ipfs add -r folder_name` to add a folder already, folder hash is `QmNbs8stghYQMSTiC28aonneZHAk2dTJmMehJLJWR3xY7u`, now I want to add some new file to this hash folder fast (not generate other file's hash), how can I do it?

**Comment by whyrusleeping** [comment]
@cxgreat2014 You can use `ipfs object patch`.

For example, if you wanted to add a file named `foo` to your directory, whose hash is `QmABC123`, you could run:

`ipfs object patch QmNbs8stghYQMSTiC28aonneZHAk2dTJmMehJLJWR3xY7u add-link foo QmABC123`

**Comment by Kubuxu** [comment]
Or using files API:

```sh
ipfs files cp /ipfs/OLDDIRHASH /tmpdir
ipfs files cp /ipfs/NEWFILE /tmpdir/newfile
NEWHASH=$(ipfs files stat --hash /tmpdir)
ipfs pin add $NEWHASH
ipfs files rm -r /tmpdir
```

**Comment by cxgreat2014** [comment]
@whyrusleeping @Kubuxu Thanks a lot

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-to-add-some-file-to-a-hash-folder-fast/420
