### ISSUE TITLE
Did ipfs have public pin service?

### ISSUE THREAD

**Issue by cxgreat2014** [ipfs/faq#212]
I have added some file to ipfs, but other people download the file from it too slow, how to let it become fast? did ipfs have public pin service?

**Comment by xloem** [comment]
there's https://ipfs.pics/

**Comment by HendrikF** [comment]
Just found https://pinbits.io/ (commercial)

**Comment by RichardLitt** [comment]
Currently we have pinbot running in the IRC channel. You can use it today to publicly ping things.

**Comment by cxgreat2014** [comment]
@RichardLitt Thanks!

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/did-ipfs-have-public-pin-service/358.
