### ISSUE TITLE
What is the mapping between block hashes and storage in .ipfs/blocks/?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#213]
Answer: `base32encode-nopad(base58-decode(HASH))`, but this will change soon (see https://github.com/ipfs/go-ipfs/issues/3463)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-is-the-mapping-between-block-hashes-and-storage-in-ipfs-blocks/409.
