### ISSUE TITLE
Which chunking algorithms are available?

### ISSUE THREAD

**Issue by JustinDrake** [ipfs/faq#214]
The `ipfs add` command has the following flag:

>  -s,     --chunker             string - Chunking algorithm to use.

What chunking algorithms are available?

**Comment by JustinDrake** [comment]
See [here](https://github.com/ipfs/go-ipfs/blob/73cd8b3e98aba252f0eadcc625472103a2dd1d53/importer/chunk/parse.go). The default is to use a block size of `DefaultBlockSize int64 = 1024 * 256`. Another block size can be specified using `size-*`. There's also the `rabin-*` chunker which uses `rabin-[min]-[avg]-[max]`.

**Comment by JustinDrake** [comment]
As far as I can tell, the Rabin chunker is a "Content Defined Chunker" to improve deduplication. See [here](https://moinakg.wordpress.com/2013/06/22/high-performance-content-defined-chunking/).

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/which-chunking-algorithms-are-available/363.
