### ISSUE TITLE
Are there any promising IPFS-based replacements for Twitter?

### ISSUE THREAD

**Issue by ratkins** [ipfs/faq#215]
What [I want](http://frabjousdei.net/post/108191939171/rfcs-not-ipos) is a fully distributed public short message broadcast platform that can't be subpoenaed or go broke and supports cryptographic verification of message integrity and sender identity. The ability to implement collaborative blocking/filtering is important; private "direct messaging" less so. It should be a protocol, for which anyone is free to implement a client on any platform (#RFCsNotIPOs!)

Am I correct in thinking IPFS would be a good basis for such a system?

Does what I want exist already? Are there any promising contenders?

**Comment by ChicoBitcoinJoe** [comment]
I'm working on a project right now that imitiates reddit using ipfs and ethereum. The UI could easily be reworked to look like twitter. It has a private voting layer and a public voting layer so far but the final design in not finalized. [Check it out if you'd like](https://github.com/ChicoBitcoinJoe/Community).

**Comment by ratkins** [comment]
I had a quick look, and I think the complexity of your requirements is at odds with what I want. My Ideal Distributed Twitter Replacement™ has an intentionally simple protocol, and the payload is by specification short and deliberately freeform—just a blob of 256 (?) bytes of Unicode. All of the Good Things about Twitter (@-replies, hashtags, ...) were thought up by users and established by convention within the limitations of the original message format, not passed down from Twitter product design by fiat.

(As an aside, I think a Distributed Twitter protocol is a more important first step, but I would also one day like to see a 21st Century Usenet for long-form conversation. Read up on [Usenet](https://en.wikipedia.org/wiki/Usenet) if you're not familiar with it or only know it as a source for pirated software; I see it as the ancestor of Slashdot and Digg and therefore Reddit, and it itself is the descendent of BBS systems like [Fidonet](https://en.wikipedia.org/wiki/FidoNet).)

**Comment by ChicoBitcoinJoe** [comment]
My DApp at its core is just a smart contract that broadcasts an ipfs hash. Very simple but powerful. Replies and hashtags would just be broadcasting on those specific channels. Reputation systems definitely have a way to go but there are many projects like mine working on this.

**Comment by jollm** [comment]
Have you looked at Mastodon? https://mastodon.social

**Comment by ratkins** [comment]
I did see Mastodon, but it's federated and built on top of a database (rather than completely distributed), so it doesn't match my criteria.

**Comment by ankushnarula** [comment]
The [AKASHA project](http://akasha.world) is building a "decentralized" social network using Ethereum and IPFS.  It's still in early public alpha (not using real currency yet) but the concept is very promising because it is built atop an economic free market.

**Comment by ratkins** [comment]
Akasha looks interesting and I will keep an eye on it. From the little they have on their site it seems to be a platform for hosting long-form content (a la Medium) rather than short-form "status updates" though?

**Comment by victorb** [comment]
I have yet to see something Twitter-like built on top of IPFS that's been deployed. There is a prototype that @haadcode worked on in the past, https://github.com/haadcode/planet-express, but it's a early prototype and I'm not sure about it's current status.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/are-there-any-promising-ipfs-based-replacements-for-twitter/351
