### ISSUE TITLE
Lost hash after init

### ISSUE THREAD

**Issue by metairie** [ipfs/faq#217]
Hi everybody.
I'm beginning with IPFS.

I started to init 2 servers and add multiple files. Get files from another account. Seems ok , lot of errors but it worked.

I shutdown the machine yesterday, and restart today. My problem is impossible to get my first hash created after the init. My question :

how to find them ? config give a peer id which is not the same
how to browse files I add yesterday ? I assume that I need the lost hash , right?

Thank you all folks.

**Comment by ghost** [comment]
You can do `ipfs refs local` to list the hashes of all objects you have stored locally. Note that this will also include chunks of files bigger than 256 KB.

Does this help?

**Comment by metairie** [comment]
humm. I get lot of hashes. hundreds.

Is anybody could reply to my question, is the initial hash is useful ?

**Comment by ghost** [comment]
You can try out the `ipfs files` commands as a way of keeping track of things you add.

**Comment by Mossfeldt** [comment]
I think you should use ipfs pin ls --type=recursive

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/lost-hash-after-init/347.
