### ISSUE TITLE
What is the difference between trickle-dag and merkle-dag?

### ISSUE THREAD

**Issue by xloem** [ipfs/faq#218]
What is the difference between trickle-dag and merkle-dag?

**Comment by Kubuxu** [comment]
tricker-dag is a merkle-dag in the definition sense but when we think about merkle-dag we default to thinking about balanced tree DAG. This isn't the case in with trickle-dag that has other structure (list-of-lists).

**Comment by xloem** [comment]
I guess I mean, what is the effective difference for the user: when should trickle-dag be used?

**Comment by mateon1** [comment]
Trickle-dag is optimized for reading data in sequence, while the merkle-dag improves random access time. It might make sense to use trickle-dag for long videos, but in my experience it's not a massive difference.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-is-the-difference-between-trickle-dag-and-merkle-dag/265.
