### ISSUE TITLE
ipfs file hashes

### ISSUE THREAD

**Issue by coderhelps** [ipfs/faq#219]
From what I understand, it is possible to change file hashes from the standard sha256-256 variant, will there be any way to relate the same file that has a different hash variants together?
As an example, if 10 people upload the same file, but 5 choose a different hash variant than the current standard sha256-256, will there be a way to relate those 10 files together to speed up the download process?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/ipfs-file-hashes/461.
