### ISSUE TITLE
Do dns-addressed links guarantee content authenticity?

### ISSUE THREAD

**Issue by dotchev** [ipfs/faq#225]
Considering that a dns link of the form `/ipns/exmple.com` contains no public key hash, how can we be sure of the authenticity of the content it points to?
Isn't it a security degradation compared to normal ipns links?

**Comment by Kubuxu** [comment]
If DNS takeover/spoofing is part of your threat model, yes.

We use DNS to resolve them to hash links, so if DNS service is compromised they hash link can be replaced.

**Comment by kcolford** [comment]
@Kubuxu On that note, do you use DNSSEC validation on your gateways (to prevent such spoofing where an administrator has set it up correctly)?

**Comment by Kubuxu** [comment]
Not sure, cc @lgierth

If we are not, we might want to do that.

**Comment by lidel** [comment]
This may be helpful: 
- https://dnssec-debugger.verisignlabs.com
- http://dnsviz.net/d/ipfs.io/analyze/

**Comment by ghost** [comment]
Yeah we might want to have IPNS check DNSSEC signatures. Low priority for now, but I'll happily support pull requests.

**Comment by Kubuxu** [comment]
I think it is more of a infrastructure thing, having local resolver working with DNSSEC.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/do-dns-addressed-links-guarantee-content-authenticity/462.
