### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by Mossfeldt** [ipfs/faq#226]
I think IPFS is great and something I would like to contribute to in any way possible. The problem is I'm not a coder or developer.

I have acces to a good internet connection, virtual servers with steady uptime and the possibility to dedicate hardware for the good cause of helping the community. 

What can I do to help? 
Already running a node and searching for stuff to pin. ;)

**Comment by whyrusleeping** [comment]
@Mossfeldt A great way to help out right now is to run a node or two, and report *any* issues you have, ask questions about everything that isnt obvious (to help us write better documentation) and if you're feeling really helpful, write up short guides on anything you think might be useful.

Stop in and say hi on IRC too if you feel like chatting :)

**Comment by Mossfeldt** [comment]
Yep, running two nodes and a gateway. Testing everything I can come up with wile searching for and reading info/guides. :)

**Comment by dimitarvp** [comment]
@Mossfeldt If I had some free server resources, I'd try and find a way to emulate several hundred or thousand nodes -- via virtual networks inside servers, probably; there are tools which are used for education of sysadmins and they could be extremely useful in such cases. Then I'd try running different scenarios like @whyrusleeping suggested, and report any bugs.

**Comment by hsanjuan** [comment]
@Mossfeldt would you like to give a go to https://github.com/ipfs/ipfs-cluster/ ? I'd be happy to hear your feedback.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-can-i-contribute/425.
