### ISSUE TITLE
Can I get the hash for my data without adding it to IPFS?

### ISSUE THREAD

**Issue by rwaltr** [ipfs/faq#227]
more for curiosities sake. But it would be nice to see the hash before making the final write.

**Comment by RichardLitt** [comment]
Do you mean something like `ipfs ls <hash>`, `ipfs get <hash>`, or `ipfs refs <hash>`? All of these work with existing hashes. Or you could check on the gateway. 

If you're curious about getting a hash of your data without adding the content to IPFS, and then checking; I'm not sure if that is possible at the moment. Someone else will know more.

**Comment by rwaltr** [comment]
Your second paragraph is what I'm looking for.

**Comment by RichardLitt** [comment]
Renamed it to be a bit clearer. Let me know if that's not OK!

**Comment by RichardLitt** [comment]
It looks like `ipfs add <data> -n` would work for you. From `ipfs add -h`:

```
  -n,     --only-hash           bool   - Only chunk and hash - do not write to disk. Default: false.
```

**Comment by rwaltr** [comment]
badass, Thanks a ton. I havent actually deployed IPFS yet, so I couldnt see the --help :/

**Comment by RichardLitt** [comment]
Just tested. This works as you would expect - I got the hash, but was unable to get it locally or through the gateway.

**Comment by victorb** [comment]
You can use the `-n` flag to `ipfs add` to just chunk and hash the file and
not add it to IPFS.

```
-n,         --only-hash           bool   - Only chunk and hash - do not
write to disk.
```

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/can-i-get-the-hash-for-my-data-without-adding-it-to-ipfs/269
