### ISSUE TITLE
External IP and strange ports

### ISSUE THREAD

**Issue by Mossfeldt** [ipfs/faq#228]
When doing ipfs id <nodehash> on one of my nodes behind pfSense firewall i get alot of different ports on my external IP(v4). Why is that? 
The node is on standard port and port is forwarded in firewall.

**Comment by mitar** [comment]
Related: https://github.com/ipfs/go-ipfs/issues/3780

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/external-ip-and-strange-ports/394.
