### ISSUE TITLE
How does IPFS compare to libswift?

### ISSUE THREAD

**Issue by tabbyrobin** [ipfs/faq#23]
They seem to have very similar goals.
- http://libswift.org/
- https://github.com/libswift/libswift

**Comment by RichardLitt** [comment]
I'm not sure. @jbenet what do you think?

**Comment by RichardLitt** [comment]
Libswift.org is no longer up, and libswift on GitHub hasn't had a contribution in over a year. I'm not sure if this question is still relevant. 

Message to reopen if curious.
