### ISSUE TITLE
How to create a private network of ipfs 

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/faq#230]
Is their any way to create the private network of ipfs nodes that is used to replicate the data on multiple nodes or is their any way to create multiple node of the ipfs on the same machine .

Thanks

**Comment by hsanjuan** [comment]
@satyamakgec do you mean something like https://github.com/ipfs/ipfs-cluster ?

**Comment by satyamakgec** [comment]
@hsanjuan thanks but ipfs cluster is still in alpha phase. 
Please guide me how to create multiple nodes on one machine and run them simultaneously.
machine - linux

**Comment by whyrusleeping** [comment]
@satyamakgec try out iptb: https://github.com/whyrusleeping/iptb

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-to-create-a-private-network-of-ipfs/339.
