### ISSUE TITLE
how do i access room on the chat.ipfs 

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/faq#231]
i already create account on chat.ipfs IRC but it needs the room to connect. Please can any one help me to give the list of rooms to connect

**Comment by hsanjuan** [comment]
Where did you create an account? In freenode? The ipfs IRC channel in freenode is #ipfs .

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-do-i-access-room-on-the-chat-ipfs/318
