### ISSUE TITLE
fuse mount, executable path on linux

### ISSUE THREAD

**Issue by satra** [ipfs/faq#235]
Can i mount a directory containing executables on an ipfs fuse mount?

for example do: 
```
ipfs daemon &
ipfs mount
export PATH=/ipfs/QmWvQ8fz9XMJoxQHV5BHKmVqYoVNWkckUxQ8LNSgEkdBgD/bin:$PATH

# or

export PKG_HOME=/ipfs/QmWvQ8fz9XMJoxQHV5BHKmVqYoVNWkckUxQ8LNSgEkdBgD/
source $PKG_HOME/setup.sh
```

ps. i can't seem to get this to work inside my current environment. i'm going to check it on a remote machine to test.

**Comment by Kubuxu** [comment]
No, the executable flag won't be set on this file. Not sure how to work around it to be able to call `source`.

**Comment by satra** [comment]
@Kubuxu - thank you. it would be interesting to see if fuse could contain executable information. i've been able to do this with s3fs in the past i believe.

(it seems i have a bigger problem right now - i can't even do an `ipfs ls` on a directory hash on two separate machines on two different networks.)

**Comment by lidel** [comment]
@satra As a workaround, you can wrap your data with [EncFS](https://en.wikipedia.org/wiki/EncFS) or create a file with [encrypted loop device using dm-crypt and luks](https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_a_non-root_file_system#Loop_device).  Both enable you to set executable flag inside of encrypted filesystem. 

If you don't care about encryption, just create a file with [loop device](https://en.wikipedia.org/wiki/Loop_device) alone.

**Comment by satra** [comment]
@lidel - thanks for the suggestion. a key point here about mounting the ipfs directory hash is to minimize the data transferred to just the bits needed for that particular execution. wouldn't a loop device or encfs require all the bits of the file to be transferred to the host? 

ideally we would just have the metadata transferred so that people can do things like `ls`, `which`, but the actual bits would be transferred only when open is called on the file descriptor whether via exec or read/write.

**Comment by whyrusleeping** [comment]
Supporting executable bits is definitely on our todo list.

**Comment by lidel** [comment]
@satra  until `go-ipfs` provides native support for executable bits, you can try to mitigate the need for big downloads by creating _separate loop device per every executable_ (yes, it is an overkill, but should be easy to orchestrate with shell scripts)

**Comment by satra** [comment]
@lidel - thanks i'll look into this.

my hope was for lazy execution. 

```
ipfs mount
export PATH=/ipfs/some_location/:$PATH
executable_on_ipfs_path arg1 arg2 
```

so initially executable is not on the system, but will be pulled by a trigger from the system path check by the fuse endpoint.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/fuse-mount-executable-path-on-linux/264
