### ISSUE TITLE
What Happens When You Add a File?

### ISSUE THREAD

**Issue by glowkeeper** [ipfs/faq#236]
The draft white paper says: "Nodes are identified by a NodeId, the cryptographic hash of a public-key". Is the same process used when I add a file to IPFS? The white paper mentions cryptographic hashes, but not digital signatures. So:

    $echo "hello WOOOOOOOORLD" | ipfs add -q

...returns `QmdHom8wF6vcMSdWjpFkxCoGcJYPDnKo5qDn3wWn8LGhgN`. Is that the signed and hashed id of the file?

**Comment by hsanjuan** [comment]
No, `QmdHom8wF6vcMSdWjpFkxCoGcJYPDnKo5qDn3wWn8LGhgN` is just the [multi]hash for "hello WOOOOOOOORLD\n".

Your node's ID is the [multi]hash for the public key the node is using (that's what the paper says).

So to answer your question, hashes are not signed and everyone can obtain the same hash given the same input.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-happens-when-you-add-a-file/418.
