### ISSUE TITLE
Can I instruct IPFS to connect to more peers?

### ISSUE THREAD

**Issue by ajthemacboy** [ipfs/faq#237]
Can I make IPFS connect to more peers, either by:

- Increasing the peer limit or scan interval with some environmental variable or config option?
- Running a command to search for more?
- Connecting/downloading numerous files?
- Any other way?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/can-i-instruct-ipfs-to-connect-to-more-peers/259
