### ISSUE TITLE
Aren't the paid pin services a possible death for IPFS?

### ISSUE THREAD

**Issue by dimitarvp** [ipfs/faq#239]
The title summarizes my worry and I'd like to elaborate my reasons for asking the question.

To clarify: a "paid pin service" is basically a company with IPFS nodes with hefty storage attached that you pay, supply with hashes, and they replicate your content on their nodes.

What I list is personal and subjective preference. I am reasonably convinced by my HackerNews and Reddit frequenting that many other techies have the same preferences as me. Still, we aren't representative for the entire IPFS community, obviously.

1. IPFS should be used to evade censorship, reduce/eliminate echo chamber effects and make it hard for oppressive regimes (like North Korea) to bribe/coerce a small amount of entities (press, influential bloggers, national TV outlets etc.)

2. IPFS should be used to nullify man-in-the-middle malware attacks. Several NSA and CIA leaks have clearly shown that _encryption works_. So the spy agencies' tactic is to plant infected software and bypass the problem altogether. I only heard (sorry, can't provide links) about some popular software installers being intercepted along the way and modified to include spyware -- that includes replacing the MD5 / SHA1 checksum that one can use to verify if the installer is correct as well. IPFS' very nature directly kills such attacks. It absolutely must have a community-curated big list of hashes pointing at popular software installers.

3. IPFS should automatically ensure content is distributed and accessible everywhere with a reasonable lag -- probably making sure it has at least 3-5 copies on other IPFS nodes in the process. I won't get angry if my IPFS node takes 3 minutes to find seeders for the file I am interested in. Unless IPFS' goal is to fully replace the WWW (doubtful), I don't think that'll ever be an issue.

The point 3 captures my worry about IPFS' future the most. I am already starting to see paid pin services and IMO that's severely disappointing and dangerous for IPFS.

**_In my eyes this must be a baseline feature of IPFS, not a paid add-on service!_**

The current implementation of IPFS is pretty good and I sure as hell wouldn't want my node to start distributing my content without me explicitly telling it to do so, yes. But if I issue a publish command of sorts, I'd expect everybody with access to IPFS to be able to find my content several minutes later at the most.

When I first heard of IPFS, I thought to myself "now THERE's the solution of many of the current Internet's problems!" -- recently though, it feels bad when I scour through the issues and read the discussions. A standard IPFS node implementation should definitely take care to _automatically disseminate content if so instructed_. And every IPFS node should have a shared host mode: a setting specifying how much gigabytes of your own storage you are willing to donate.

I understand this is much more easily said than done of course. I believe IPFS must aim to be a solid tech with a clear vision and right now I feel that vision is somewhat lacking. It shouldn't be "good enough", it should be "the next evolutionary step". We have enough half-finished technologies as it is.

Don't the IPFS authors and contributors want to stand out and make a real difference?

**Comment by lidel** [comment]
While I sympathize with underlying sentiment of point 3, you can't have your cake (control what your node is sharing) and eat it too (force everyone else to blindly host your bytes forever)  🙃 

That being said, there are ways that provide middle ground:

- https://github.com/ipfs/ipfs-cluster/: enables you to transparently pin content to multiple nodes _you own and control_ 
- _Preload your data at one or multiple public gateways_  (no pin, but gives you temporary copy of your data for free). This can be done manually with browser or `curl` or via something like  https://github.com/BrendanBenshoof/cachewarmer

**Comment by dimitarvp** [comment]
@lidel Thanks, these two can definitely help. I plan on setting up a home server in the next months; and I can install these pieces of software on my PC and Mac as well. That should give me 3 replicas of everything I would like backed up. At least locally.

I do believe we need to bring all of this one step further however. What about having a project similar to `cachewarmer` but it would also list people/organizations willing to donate part of their bandwidth and storage (I am guessing with peer IDs)? Or, better yet, make them automatically discoverable?

Do you know if the IPFS protocol allows for peer discovery based on custom criteria?

EDIT: Nevermind my question, this issue covers it up pretty well: ipfs/notes#15

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/arent-the-paid-pin-services-a-possible-death-for-ipfs/298.

**Comment by asdfzxh8** [comment]
nst as reason or not, ask anyx, no worryx
