### ISSUE TITLE
should ipfs cat dirhash work?

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/faq#240]
When ipfs cat 'any-dirhash'  is performed I get the following error : Error: this dag node is a directory
.

**Comment by whyrusleeping** [comment]
@satyamakgec This goes back to very old 'unix holy wars'. In BSD systems, you can cat a directory, and get raw directory information. On linux, this is not the case. We have chosen to take the linux style approach, though I don't disagree with the other camp

**Comment by satyamakgec** [comment]
@whyrusleeping  so what i have to do to get rid of it

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/should-ipfs-cat-dirhash-work/342.
