### ISSUE TITLE
How can I remove a directory and all its contents?

### ISSUE THREAD

**Issue by jamiewilson** [ipfs/faq#241]
I have this object, a directory with the following contents:

```shell
$ ipfs file ls fZXmMYYCQYeUUadmvx23LXR3CQRGoK881mJoKAPT8fZGR6
css
img
index.html
```

But when I go to remove this folder with the [`ipfs files rm`](https://ipfs.io/docs/commands/#ipfs-files-rm) command, I get the following message:

```shell
$ ipfs files rm -r fZXmMYYCQYeUUadmvx23LXR3CQRGoK881mJoKAPT8fZGR6
Error: Paths must start with a leading slash.

$ ipfs files rm -r /fZXmMYYCQYeUUadmvx23LXR3CQRGoK881mJoKAPT8fZGR6
Error: merkledag: not found
```
Does anyone know what I'm doing wrong here? Thanks for the help.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-can-i-remove-a-directory-and-all-its-contents/336
