### ISSUE TITLE
Is garbage collection work for upload foleder as well ?

### ISSUE THREAD

**Issue by satyamakgec** [ipfs/faq#242]
Hi Folks , I am new in ipfs . i am creating an application that push the folder over the ipfs . I am concern for the garbage collection that it may automatically delete my content on ipfs please give me a brief over view to manage the ipfs gc

Thanks

**Comment by Kubuxu** [comment]
`ipfs add` has `--pin` option it is default to true so it pins added file/directory right away. Pinned files and directories won't be removed by the GC.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-garbage-collection-work-for-upload-foleder-as-well/334
