### ISSUE TITLE
Can I get a list of all active IPNS nodes?

### ISSUE THREAD

**Issue by traverseda** [ipfs/faq#244]
I want to bootstrap a distributed web application, but first I need to be able to get a manifest of all participating nodes by checking for a particular files in an IPNS dir.

 * Can I get a list of IPNS nodes, and have my spider check them for a particular file, or do I need to provide a "bootstrap" web service?
 * Can I tell if an IPNS 'folder' has changed, similar to `If-Modified-Since` in http?

**Comment by traverseda** [comment]
ipfs diag net

**Comment by flyingzumwalt** [comment]
This issue has been copied to https://discuss.ipfs.io/t/can-i-get-a-list-of-all-active-ipns-nodes/415
