### ISSUE TITLE
what is Type in dht/findpeer 

### ISSUE THREAD

**Issue by thisconnect** [ipfs/faq#245]
What is the Type (Int) described in the Response of dht/findpeer?
https://ipfs.io/docs/api/#apiv0dhtfindpeer

And will the js-ipfs-api support api.dht.findpeer in the future? 
https://github.com/ipfs/js-ipfs-api

**Comment by thisconnect** [comment]
I'm not sure where to read and get more info about DHT... is that more libp2p specific?

**Comment by Kubuxu** [comment]
It is this: https://github.com/libp2p/go-libp2p-routing/blob/master/notifications/query.go#L16

Where numbers increase from 0 for every line.

**Comment by thisconnect** [comment]
Thanks @Kubuxu !


reference for myself

#### Type:
0	PeerResponse
1	FinalPeer
2	QueryError
3	Provider
4	Value
5	AddingPeer
6	DialingPeer

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/what-is-type-in-dht-findpeer/
