### ISSUE TITLE
How, or what can I browse on IPFS currently?

### ISSUE THREAD

**Issue by Katamori** [ipfs/faq#246]
Newcomer here; the demo and the introduction of the project were really promising for me, especially your statements on supporting the developing world and the content creators.

However, as a civilian, it'd be much more worthy for me if I can find some content on your network! Is there any major source for sites and/or "services" currently available on IPFS?

The list of every peer is an amazing feature, yet not the most useful in its current form.

**Comment by lidel** [comment]
Hi, https://github.com/ipfs/awesome-ipfs should be a good starting point.
There is also a recently created discussion forum at https://discuss.ipfs.io, where community can discuss new initiatives (recent example: [Minecraft archive on IPFS](https://discuss.ipfs.io/t/minecraft-archive-on-ipfs/105?u=lidel)).

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-or-what-can-i-browse-on-ipfs-currently/328
