### ISSUE TITLE
API not Running

### ISSUE THREAD

**Issue by jeddah-liu** [ipfs/faq#247]
When I run the ipfs in windows Command line console with the _ipfs cat peers_ command, an _api is not running_ echo to me;
Then I try to use the command _ipfs daemon_ to start a long run daemon process, Error comes again, showing that _can't acquire lock: file "C'\Users\\MyPC\\.ipfs\\repo.lock" already locked_. 
What happened in this process?
I check the root dirctory of the .ifps, and find that there are a repo file and a repo.lock file there. I open both file with notepad++, which shows me someting like that"{OwnerPID:11xxx}".
PS: What I installed on my PC is the go-ipfs v0.4.8. My PC OS is win7 Ultimate x64.

**Comment by mateon1** [comment]
When you see the message `repo.lock is already locked`, you should run `ipfs repo fsck` after making sure the repo is not in use.
On Windows there seems to be an issue, where sometimes the lock is not released after an IPFS command finishes, but this will not happen if the ipfs daemon is running.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/api-not-running/253
