### ISSUE TITLE
Is IPFS good for fast-changing files / databases?

### ISSUE THREAD

**Issue by ghost** [ipfs/faq#251]
What is the best way to run dynamic applications?
Can we just take the raw files from a DBMS and publish a snapshot each time a COMMIT; is issued?
Or should DMBSs accomodate to the new p2p-way the data is stored in deeper layers?
Is it better to have a central database from which authoritative snapshots are distributed amongst the peers?
Or is it better to have distributed databases running independently from IPFS altogether, resulting in a complete separate system? Databases are powering the web of today, not static files. We need to deal with the database issue. See semantic web for related discussion.

What are the most pressing issues to come up with a solution for this?
Are we at the stage of incomplete designs of our ideas?
Are we at the stage of incomplete implementations of our designs?
Are we at the stage of incomplete advertisement of our solution?

Please let me know, I'm interested what your answers will be.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-ipfs-good-for-fast-changing-files-databases/254

**Comment by unfa** [comment]
Could IPNS be a way to deal with this kind of use-cases?
