### ISSUE TITLE
Node traversal

### ISSUE THREAD

**Issue by gediminaspetrikas** [ipfs/faq#259]
Hey,

I aim to understand how NAT node traversal works in IPFS. I've found https://github.com/wking/ipfs-specs/tree/master/protocol/network but it does not exactly answer my question. In comparison, here's an illustration how Freenet's node traversal work: 
![image](https://cloud.githubusercontent.com/assets/11786028/26274768/31ad627a-3d5a-11e7-80bd-a2a776fcd71e.png)
Can this be compared to how IPFS' traversal work, or is there any differences?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/node-traversal/257
