### ISSUE TITLE
Which is the default transport protocol?

### ISSUE THREAD

**Issue by teaalltr** [ipfs/faq#26]
This is mostly about the go implementation. I'd like to know which is the default transport protocol used by IPFS (UDP, uTP or TCP); that's because it opens lots of TCP connections, according Windows' net manager. At a certain point, while doing nothing, I got a 100 open TCP connection peak. Don't think it's normal. Thoughts?

**Comment by jbenet** [comment]
@Piruzzolo right now, go-ipfs runs mostly on TCP connections. So this is normal. Is this a problem for you?

(By the way, the overhead that people have with things like uTP tends to be a bit less, because they manage connections in user space, not in the kernel, which is cheaper.)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/which-is-the-default-transport-protocol/304.
