### ISSUE TITLE
How are online sales handled?

### ISSUE THREAD

**Issue by PopeFelix** [ipfs/faq#27]
If I want to buy a thing, I want to be sure that my money is going to get to the actual seller.  If I'm selling a thing, I want to make sure that my customers are buying it from me.  How does that happen?

**Comment by jbenet** [comment]
With IPFS, you can do anything you do today with HTTP.

Though you can do more: eg use transactions which work offline.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-are-online-sales-handled/417.
