### ISSUE TITLE
How can I maintain a pointer to a file?

### ISSUE THREAD

**Issue by philholden** [ipfs/faq#3]
Suppose I had a slideshow stored in ipfs where each slide was an html file stored in an ipfs directory. How would I go about maintaining a pointer to the current slide, such that a browser polling a certain URL would always see the current slide?

If so is there any way to subscribe to change events for this pointer?

**Comment by jbenet** [comment]
@philholden did you get your question answered?

In any case: take a look at the Simple JS Apps in http://ipfs.io/docs/examples/ -- they use a `#<path>` "argument".

**Comment by philholden** [comment]
Thanks for responding the project seems really interesting (I have now listened to the three talks).

I will try to rephrase the question.

I'd like web clients to refetch data when an IPNS entry changes. I am guessing I'd need a Go server with websockets.

From Go can I subscribe to IPNS locator change events or do I just have to poll?
Is there a better way built into IPNS of getting these change events to the client?

**Comment by whyrusleeping** [comment]
currently there is no way to be notified of a change in an ipns entry, although we have plans for a pub/sub system through the DHT. This is still a little ways out.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-can-i-maintain-a-pointer-to-a-file/408.
