### ISSUE TITLE
What is a Merkle DAG?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#31]
A Merkle DAG is a Merkle directed acyclic graph. That is a data structure similar to a [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree) but not so strict: such DAG does not need to be balanced and its non-leaf nodes are allowed to contain data.

Correct?

**Comment by jbenet** [comment]
Correct!

**Comment by Mithgol** [comment]
And a hyperlink to the [spec of the IPFS Merkle DAG](https://github.com/ipfs/specs/tree/master/merkledag) for future references.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-is-a-merkle-dag/386.
