### ISSUE TITLE
Can an IPFS installation be portable? (IPFS_PATH)

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#33]
A [portable application](https://en.wikipedia.org/wiki/Portable_application) is the one that is designed to run on a compatible computer without being installed in a way that modifies the computer's configuration information. Such application can be stored on any storage device (including internal mass storage and external storage such as USB drives) – storing its program files and any configuration information and data on that storage medium alone.

I imagine some users would want to have the same local storage (and pinned media) at home and at work by bringing a mere USB stick where full [BYOD](https://en.wikipedia.org/wiki/Bring_your_own_device) is not practical.

**Comment by whyrusleeping** [comment]
go statically compiles by default, an ipfs binary should run on any compatible system. 

We provide prebuilt binaries here: https://gobuilder.me/github.com/jbenet/go-ipfs/cmd/ipfs

**Comment by Mithgol** [comment]
And where is the application's local storage created? (I haven't yet tried the prebuild binary; the answer may become obvious when I try.)

**Comment by whyrusleeping** [comment]
it stores everything either in `$IPFS_PATH` or `~/.ipfs` if the environment variable is not set

**Comment by Mithgol** [comment]
A portable application would use `$IPFS_PATH`, then `./.ipfs` (if exists as a subdirectory in the application's directory), then `~/.ipfs`.

What is the correct repository to open a feature request about it?

**Comment by jbenet** [comment]
> then `./.ipfs` (if exists as a subdirectory in the application's directory)

There are uses for this, and i'd also like to follow git semantics, but I'm not yet convinced it's TRTTD. there's an issue about this in this tracker, i think. if not, open one, sure

**Comment by whyrusleeping** [comment]
@Mithgol the go-ipfs repo would be the correct repo to file an issue in.

**Comment by Mithgol** [comment]
Thanks, an issue is created (ipfs/go-ipfs#1707).

This FAQ entry may now be closed.

**Comment by jbenet** [comment]
Should we close or leave issues open in this repo? (i'm still wondering tradeoffs of what to do). will people search properly?

**Comment by Mithgol** [comment]
They will if they decide to erase `is:open` from the search bar.

**Comment by Mithgol** [comment]
However, as the README says,

> All these questions and answers will be compiled into a webpage rendered at http://ipfs.io/docs/install

so maybe the issues should be kept open until that compilation.

On the other hand, maybe it's quite the contrary because only the answered (and closed) FAQs should be treated as the ones ready for compilation.

**Comment by jbenet** [comment]
I'll reopen to make this easier to find

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/can-an-ipfs-installation-be-portable-ipfs-path/468.
