### ISSUE TITLE
Is it possible to limit the size of a local storage?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#34]
A local storage is naturally limited by the size of the physical disk drive it resides on. However, an end user may want to limit it further. The limit may include (or not include) the collective size of pinned media ([`ipfs pin`](https://ipfs.io/docs/commands/#ipfs-pin)).

**Comment by jbenet** [comment]
Yes, this will merge soon in go-ipfs.

**Comment by RichardLitt** [comment]
@whyrusleeping Has this been merged?

**Comment by Wallacoloo** [comment]
@RichardLitt AFAICT you just set DataStore/StorageMax inside of `~/.ipfs/config` to whatever you want your limit to be. The default appears to currently be 10 GB.

**Comment by ghost** [comment]
The `Datastore.StorageMax` setting does not limit how much diskspace the datastore can use. It's used only by the GC, together with `Datastore.GCWatermark`, to determine whether or not to run GC.

**Comment by ghost** [comment]
> @whyrusleeping Has this been merged?

I don't think this ever took off. It will very likely come with the "constrainted environments" effort.

**Comment by Wallacoloo** [comment]
@lgierth Hopefully not off-topic for this issue, but is there any place where the various config options are documented? There's [this](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/config/readme.md), but it's pretty lacking.

**Comment by icf20** [comment]
is there any update about this ?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-it-possible-to-limit-the-size-of-a-local-storage/364
