### ISSUE TITLE
Are there plans to cooperate with Memento protocol

### ISSUE THREAD

**Issue by severak** [ipfs/faq#35]
It seems there is something called [Memento protocol](http://mementoweb.org/about/). It's defined by [RFC 7089](http://tools.ietf.org/html/rfc7089).

It's [already implemented](http://mementoweb.org/depot/) by some notable web archives (archive.org, Library of Congress Web Archive, archive.is).

Are there any plans to support this (or cooperate somehow)?

**Comment by jbenet** [comment]
We should definitely support this. https://github.com/ipfs/archives

**Comment by davidar** [comment]
:+1:

**Comment by nickkolok** [comment]
But Memento doesn't use hashes, does it?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/are-there-plans-to-cooperate-with-memento-protocol/325.
