### ISSUE TITLE
Can IPFS crack passwords (i.e. help an attacker guess a password of which only a hash is known)?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#37]
_([inspired](https://twitter.com/taoeffect/status/614845183742509056) by Greg Slepak)_

~~Yes: if a known hash is a [multihash](https://github.com/jbenet/multihash/) and if a text file containing the password (and only the password) was ever published, then a mere IPFS lookup will return the password in plain text form.~~

~~Even if the login's owner have not ever published the password, such file may eventually be published by someone else.~~

**Update:** no, the hash is actually more complex; see below.

**Comment by jbenet** [comment]
Actually No, the plaintext file is wrapped with metadata so the hash changes.

And this is silly:

>  Even if the login's owner have not ever published the password, such file may eventually be published by someone else.

If someone deliberately puts the pwd out like that, they could just as well tweet it out and tag you personally.

Maybe ask first before asserting one way or another?

**Comment by Mithgol** [comment]
> the plaintext file is wrapped with metadata so the hash changes

Sorry, I've misunderstood the dependence of that hash from the file's contents.

I've edited my original (wrong) answer and added a strikethrough to indicate the misunderstanding.

By the way, what are the elements of metadata that affect the hash?

For example, does the hash change if a file is renamed?

**Comment by Mithgol** [comment]
…I've just `ipfs add` two equal files and got two equal hashes, so the metadata must be something else, not the name.

**Comment by whyrusleeping** [comment]
if you do

```
echo "hunter2" | ipfs add
```

you will not get the hash of `hunter2`, you will get the hash of the merkledag protobuf containing the data `hunter2` (plus some unixfs framing)

**Comment by Mithgol** [comment]
Ah, I see. I get it. It's not even a hash of that file's content. It's a hash of an object that has links and blocks and whatnot.

**Comment by jbenet** [comment]
yep, thanks for editing :smile: :+1:

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/can-ipfs-crack-passwords-i-e-help-an-attacker-guess-a-password-of-which-only-a-hash-is-known/300.
