### ISSUE TITLE
How do I undo the `ipfs daemon` command?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#39]
How do I ~~shot web~~ terminate the unixweb daemon? Is there any `ipfs daemon stop` to undo `ipfs daemon`?

**Comment by ghost** [comment]
You send it Ctrl-C to terminate gracefully, and a second Ctrl-C to terminate immediately.

**Comment by jbenet** [comment]
@Mithgol or `kill $pid` or `kill -9 $pid`

**Comment by jbenet** [comment]
(i suppose it may be convenient to have an `ipfs daemon stop` or something, for scripts and so on, but not 100% convinced yet).

**Comment by Mithgol** [comment]
@jbenet Would you recommend [`taskkill /pid processID /f /t`](https://technet.microsoft.com/ru-ru/library/bb491009.aspx) on Windows, or without `/f`, or without `/t`, or without both?

**Comment by ligi** [comment]
+1 for ipfs daemon stop
use-case: I run the daemon via gomobile and there is no shell for kill commands or to send ctrl-c

**Comment by jbenet** [comment]
After speaking with @ligi, it is clear that many applications will need to be able to trigger deamon to exit through the api.

i'd be in favor of a `ipfs daemon stop`

**Comment by ligi** [comment]
that's great - would also be great to have a way to query the status of the daemon ( z.b. inactive, initializing, initialized ) - currently e.g. the initializing state is hard to detect AFAIK

**Comment by Kubuxu** [comment]
It is hard to detect as the peer discovery and inital connections run before API is started. There is very old issue about that: https://github.com/ipfs/go-ipfs/issues/973

Which means that you can't query daemon information until it started.

The `ipfs daemon stop` could be created by creating pid file inside a repo structure, it wouldn't be that hard to do.

Then, IMO, we should provided build in daemonisation of the daemon (forking mode).

**Comment by xznhj8129** [comment]
Seriously, we don't have this yet? Come on...

**Comment by alexgarciac** [comment]
Seriously needed... ipfs daemon stop

**Comment by whyrusleeping** [comment]
There are quite a bit of other things that have taken priority, I'll try and get this prioritized soon. That said, we do accept PRs ;)

**Comment by hsanjuan** [comment]
Unless you are in a situation like ligi describes (exec-ing the daemon inside an Android app), there are multiple workarounds for this. One is using a systemd service as shown at https://github.com/ipfs/examples/tree/master/examples/init to start/stop ipfs, which will additionally also collect your logs.

**Comment by xznhj8129** [comment]
...and on windows?

**Comment by hsanjuan** [comment]
I don't use windows, but http://tweaks.com/windows/39559/kill-processes-from-command-prompt/ says you can do something like `taskkill /IM ipfs`. There are shell aliases or you can put it in a script called `ipfsstop.cmd`.

That said, I don't know if exit is handled correctly in this case or ipfs will be killed immediately. Can you test?

**Comment by noxonsu** [comment]
taskkill /IM ipfs.exe /f

this work for me. But what about /Users/.../repo.lock file? How to "unlock" him? I try this, but not working

    function getUserHome() {
     return process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
    }

    if (fs.existsSync(getUserHome()+"/.ipfs/repo.lock")) {
	fs.unlink(getUserHome()+"/.ipfs/repo.lock");
    }

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-do-i-undo-the-ipfs-daemon-command/443.
