### ISSUE TITLE
Will something like inotify be available?

### ISSUE THREAD

**Issue by unode** [ipfs/faq#40]
If applications are to monitor shares that can be written to, will there be any mechanism to notify the application of the arrival of new content?
Basically I'm thinking of something equivalent to [inotify](https://en.wikipedia.org/wiki/Inotify).

**Comment by RichardLitt** [comment]
I don't see why something like this couldn't be built. At the moment, we don't have a plan to do this, AFAIK.

**Comment by Kubuxu** [comment]
`inotify` on IPNS would be great, but first we would have to make IPNS behave better :smile:

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/will-something-like-inotify-be-available/369.
