### ISSUE TITLE
Posting form data

### ISSUE THREAD

**Issue by asgraf** [ipfs/faq#41]
Every good blog need to have comments section below its articles.
How to implement simple comment posting functionality?
Is it possible to allow users visiting my ipfs site to add comments below my articles (without using social widgets served via http)

**Comment by jbenet** [comment]
this is a special case of the question "can ipfs handle dynamic content". yes: 
- https://github.com/ipfs/faq/issues/16
- https://github.com/ipfs/faq/issues/28

**Comment by balupton** [comment]
Everyone keeps referencing to this IPNS thing which is the size of a footnote in some white paper. There really needs to be a working example of what is said here, specifically demonstrating comments, before one can take it more than just an aside.

**Comment by balupton** [comment]
For a route for making that a reality, it seems IPFS should really be considered as just for hosting static content. Yes IPNS allows mutable links, but again, for static content.

For possible implementations of comments it seems IPFS cannot solve that without already knowing the hashes or IPNS locations of the contributed content which is impossible with IPFS/IPNS alone, unless one queries the entire network, which is crazy.

So things like ethereum or bigchaindb or some heroku web server seem the option here, where users can contribute an item too that is discoverable by the application.

**Comment by balupton** [comment]
Another way to say it, is IPFS will never be able to, or rather should never be able to, host an API. An external solution, be it a centralised, decentralised, distributed, or federated one, will be needed for APIs.

**Comment by fazo96** [comment]
> There really needs to be a working example of what is said here, specifically demonstrating comments, before one can take it more than just an aside.

@balupton, it looks loke you're looking for http://github.com/fazo96/ipfs-boards :+1:

**Comment by balupton** [comment]
@fazo96 thanks!

Seems it is still rocky right now, with https://github.com/ipfs/POST/ being the planned collaboration on something more stable to accomplish APIs using IPFS

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/posting-form-data/289.
