### ISSUE TITLE
What is the default gate?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#42]
Should I direct people to `http://gateway.ipfs.io/(ipfs|ipns)/$RESOURCE` when they haven't (yet) configured their local IPFS installations? Or would `http://ipfs.io/(ipfs|ipns)/$RESOURCE` (without `gateway.`) always suffice? (As it does now.)

**Comment by ghost** [comment]
Direct them to ipfs.io -- gateway.ipfs.io is deprecated and will start redirecting to ipfs.io soon. We won't shut it down though, for the foreseeable future.

**Comment by Mithgol** [comment]
I hereby summon @lidel because the README of https://github.com/lidel/ipfs-firefox-addon/ seems to indicate that only `gateway.ipfs.io` is supported (i.e. replaced) by that addon.

**Comment by ghost** [comment]
Yep that should be updated

**Comment by lidel** [comment]
Good catch. I updated README to cover old and new URLs. 
The addon already supports `https://ipfs.io/(..)`

**Comment by Mithgol** [comment]
I hereby summon @dylanPowers because the README of https://github.com/dylanPowers/ipfs-chrome-extension/ seems to indicate that only `gateway.ipfs.io` is supported (i.e. replaced) by that Chrome extension.

**Comment by jbenet** [comment]
@Mithgol things get outdated. Submit a PR to fix it, or open issue there

—

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-is-the-default-gate/467.
