### ISSUE TITLE
P2P WORM Storage?

### ISSUE THREAD

**Issue by poing** [ipfs/faq#43]
I noticed that altered files generate a new hash.  Limiting the ability to modify content, all links to any new content will need to be updated.

With the exception of the mutability of the peerID namespace, is IPFS essentially a P2P from of WORM storage?  Write Once/Read Many

The Freenet Project faced issue with the same type of immutability, resulting in [multiple key types](https://freenetproject.org/understand.html) to point to updated/updateable content.

**Comment by jbenet** [comment]
Though today is just one per node, you'll be able to have as many mutable keys as you want. Working in it.

—

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/p2p-worm-storage/466
