### ISSUE TITLE
Is simply running the daemon helpful?

### ISSUE THREAD

**Issue by panicsteve** [ipfs/faq#44]
Let's say I run the daemon but I don't pin anything.  Does this help the swarm in any way?  Will I get blocks from popular files sent my way to help with their distribution, or is it just "sitting there"?

Am I only contributing to the global IPFS swarm if I pin things?

**Comment by jbenet** [comment]
In the future you might opt to do this, but for the moment the only contribution is to the dht (which hosts routing records)

—

**Comment by whyrusleeping** [comment]
Simply running a daemon for long periods of time (the longer the better) is helpful to the DHT, the more long lived stable nodes we have, the more reliable routing resolution becomes. Once ipns is more stable (sooon!) you will be helping keep ipns records alive.

**Comment by panicsteve** [comment]
Thanks for the info!

If my node is behind NAT, will it still help, or does port 4001 need to be forwarded to the node?

**Comment by whyrusleeping** [comment]
@panicsteve if your router has upnp and/or nat-pmp, then you wont need to forward the port. If not, then yeah, forwarding the port will help out

**Comment by Mithgol** [comment]
@panicsteve If you run the daemon but don't pin anything, you still have some cache (which is not as permanent as pinned media, but it's still there). If you browse the Web using IPFS-related [Firefox addon](https://github.com/lidel/ipfs-firefox-addon) or [Chrome extension](https://github.com/dylanPowers/ipfs-chrome-extension), your cache is populated by IPFS media (from the sites that you visit if they use IPFS to store their images and other media) and your daemon helps to distribute it.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/is-simply-running-the-daemon-helpful/360.
