### ISSUE TITLE
Forgoing reputation and indiscriminately servicing leaches

### ISSUE THREAD

**Issue by gitchampion** [ipfs/faq#45]
Hi. I'm interested in using IPFS in a traditional provider-consumer setting. I want to provide content to the public without discriminating against consumers that are not contributing to the network (those that have bad scores), or consumers that have nothing to "swap".

Is this possible? Can I configure the IPFS daemon to treat all peers indiscriminately?

Thank you.

**Comment by jbenet** [comment]
@gitchampion yes absolutely. right now default seeding is the behavior, as we have not yet finished bitswap.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/forgoing-reputation-and-indiscriminately-servicing-leaches/444
