### ISSUE TITLE
pub/sub pattern support?

### ISSUE THREAD

**Issue by pocketmax** [ipfs/faq#49]
Does IPFS support pub/sub architecture? If I subscribe to a file or blob of data, if any changes are made, a notice will be sent to my device that an update was made? So if I subscribed to a video channel on an IPFS youtube channel, when a new video is uploaded to that channel, my device would get a notice to fetch the content from either a central server or a neighboring device.

**Comment by jbenet** [comment]
Yes pub/sub is planned. designs still TBD.

**Comment by hackergrrl** [comment]
Check out https://github.com/ipfs/notes/issues/64 -- there's lots of ongoing discussion on the subject!

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/pub-sub-pattern-support/359.
