### ISSUE TITLE
Storing a few TB of data?

### ISSUE THREAD

**Issue by e12e** [ipfs/faq#5]
If I push a few TB of data into ipfs (say some media files, install isos etc) -- is that a reasonable use of the technology? How could/should I assure that the network has the capacity to safely store the data, with suitable redundancy? If I dedicate a few TB of disk on my server to ipfs -- can I make sure that some sensible portion is reserved for my use?

**Comment by whyrusleeping** [comment]
Data added to ipfs is only stored locally until another interested party requests it from you. ipfs itself (the protocol) provides no guarantees of redundancy or remote storage.

**Comment by jbenet** [comment]
I'll add that _that's_ why [Filecoin](http://filecoin.io) exists-- as a way to incentivize networks of people to replicate/backup your data.

**Comment by sudhirj** [comment]
BTW, could someone confirm that `ipfs add` makes a copy of the data I'm adding? So to add 1TB of data into IPFS I'll need at least 2 TB on my disk?

**Comment by whyrusleeping** [comment]
@sudhirj that is correct. Similar to adding files into git, in the future we may find a way to work around this.

**Comment by sudhirj** [comment]
Okay. Then let's put down alternative options for others as well (I'm looking at it for large-file data distribution). The alternatives to this are 
1. Mount the IPFS datastore as a FUSE drive (requires root permissions and special installation) - will this take care of everything automatically? Is copying a file into the mounted folder same as `ipfs add`, for instance?
2. Assuming a FUSE mount, can regular IPFS commands like `ipfs pin` be used on data on the mounted drive?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/storing-a-few-tb-of-data/476.
