### ISSUE TITLE
Does IPFS complement the current structure of the internet or replace it?

### ISSUE THREAD

**Issue by pocketmax** [ipfs/faq#50]
If it replaces the current structure of the internet, How will communication between long distances be handled. If I want to send an email to someone in another state, there are no neighboring links to hop from to get the data over there.

**Comment by jbenet** [comment]
IPFS is an overlay network on top of other networks, most importantly IPv4, IPv6. it is _part of_ the internet. (so, "complement").

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-complement-the-current-structure-of-the-internet-or-replace-it/297
