### ISSUE TITLE
can IPFS split large files across multiple nodes?

### ISSUE THREAD

**Issue by pocketmax** [ipfs/faq#52]
If so, can it download the pieces of the file simultaneously like bittorrent?

**Comment by jbenet** [comment]
- **Q: Are files split into pieces?**
  Yes, files are _chunked_ when they are imported to IPFS. There are many _chunking algorithms_ for different purposes.
- **Q: do IPFS nodes download pieces of files simultaneously like BitTorrent?**
  Yes. See the IPFS Paper ([currently, draft 3](https://ipfs.io/ipfs/QmR7GSQM93Cx5eAg6a6yRzNde1FQv7uL6X1o4k7zrJa3LX/ipfs.draft3.pdf)) or [the talks](https://ipfs.io) for more details.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/can-ipfs-split-large-files-across-multiple-nodes/455
