### ISSUE TITLE
Discovery Protocols -- how does IPFS detect neighbors?

### ISSUE THREAD

**Issue by pocketmax** [ipfs/faq#53]
How does IPFS detect neighboring devices to pull content from?

**Comment by jbenet** [comment]
IPFS uses a set of **discovery protocols** to achieve this. These are pluggable, configurable, optional, and so on. For example, go-ipfs ships with:
- **Bootstrap Lists** to start with an initial set of peers. (configurable)
- **mDNS** to discover peers in local area networks.
- **DHT random walk** to learn about more peers in the network

More will come

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/discovery-protocols-how-does-ipfs-detect-neighbors/378
