### ISSUE TITLE
bluetooth LE

### ISSUE THREAD

**Issue by pocketmax** [ipfs/faq#54]
Does IPFS leverage bluetooth LE technology to transfer data and detect neighboring nodes?

**Comment by jbenet** [comment]
@pocketmax yep, they will. this is not yet implemented, but IPFS is -- by design -- transport independent and it's very easy to add this as a transport. anybody with a bit of Go experience could add it to go-ipfs.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/bluetooth-le/376
