### ISSUE TITLE
meta - rendered page

### ISSUE THREAD

**Issue by ethers** [ipfs/faq#55]
readme says "All these questions and answers will be compiled into a webpage rendered at http://ipfs.io/docs/install"

I don't see where these Q&A are in http://ipfs.io/docs/install ...

**Comment by jbenet** [comment]
they're not, yet. "_will_". we should perhaps do this. mind asking for it over at https://github.com/ipfs/website/ ?

**Comment by ethers** [comment]
done https://github.com/ipfs/website/issues/67   Feel free to close this if that's you meant.  Thanks.

**Comment by jbenet** [comment]
yep, thanks!
