### ISSUE TITLE
Initial seeks can be overly slow

### ISSUE THREAD

**Issue by vtsukur** [ipfs/faq#57]
From time to time it can be observed that initial seek for a file can be overly slow.

For example, when file is `ipfs add`-ed on a locally running machine, and then retrieved via gateway.ipfs.io/ipfs, request can take any time in between several hundreds of milliseconds down to 2 minutes timing out several times in a row (ending in successful seek, eventually).

If file is `ipfs get`-ed :) from a node that does not share same network, it is usually much much slower. Succeeds, but amount of attempts is usually bigger.

I am curious to know why these latency issues are present at the moment. Thanks!

**Comment by jbenet** [comment]
this sounds like NAT problems and nodes not finding you. these will get a lot better, and in the general case they already are.

**Comment by jbshirk** [comment]
I have observed the same, but assumed this was just normal propagation time. But if it's NAT problems, where should people go to learn how to resolve that?

**Comment by RichardLitt** [comment]
@whyrusleeping I believe some of this was fixed in 0.4.0 and 0.4.1. Can you confirm?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/initial-seeks-can-be-overly-slow/480.
