### ISSUE TITLE
How IPFS points to websites & search for content?

### ISSUE THREAD

**Issue by AsifulNobel** [ipfs/faq#58]
I was wondering when someone initializes a new IPFS node for an existing website and host it on their computer, then when people access the website using website domain name, which one will be served to people? The original website or the copied one?

**Comment by asgraf** [comment]
Client can pick both nodes as source to maximize download speed or just pick nearest & fastest one.

For example:
If you use jquery library on your website it doesn't really matter if your visitor will download it from you or from any other ipfs website that uses same version of jquery.
As long as file hash is identical your visitor can download this file from any ipfs node that has copy of it.

**Comment by RichardLitt** [comment]
Keeping this open as it is answered, and this makes it more easily searchable.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-ipfs-points-to-websites-search-for-content/383.
