### ISSUE TITLE
What is the difference between js-ipfs-api and js-ipfs?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/faq#60]
There are two repositories in the ipfs organization: [node-ipfs-api](https://github.com/ipfs/node-ipfs-api) and [ipfs-api](https://github.com/ipfs/node-ipfs). What's the difference between the two? Are they interchangeable? If one is a node implementation and the other a node digester, will node-ipfs-api eventually use node-ipfs?

**Comment by whyrusleeping** [comment]
the node-ipfs-api is api bindings for the ipfs api written in node.

node-ipfs is the actual node.js implementation of the ipfs protocol

**Comment by victorb** [comment]
I'm thinking if the repos should change name to JS to reflect the scope. Focus seems to be on node+browser and then it's really javascript, not just node.

**Comment by jbenet** [comment]
good points. it would also help to ease confusion to call all the things
"js-" instead of "node-" as "node" has many meanings in IPFS land.

**Comment by RichardLitt** [comment]
These are all called `js-` now. 👯

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/what-is-the-difference-between-js-ipfs-api-and-js-ipfs/441.
