### ISSUE TITLE
Soft links or hard links?

### ISSUE THREAD

**Issue by bunder** [ipfs/faq#61]
I want to add a large directory to IPFS. The directory has a lot of links in it. Which type of links should I use for optimal performance? Soft or hard?

**Comment by jbenet** [comment]
@bunder ipfs doesn't care, i think. 

we dont yet have directory sharding, which is going to give you really bad perf on huge dirs. if it's possible, shard the dir yourself for now (by putting things into multiple subdirectories with some fanout factor) (alternatively, help us implement support.)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/soft-links-or-hard-links/309
