### ISSUE TITLE
sharing files from their current locations

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#62]
Imagine a user that has ten terabytes of media files to share and those media files are located on different physical drives (four drives, for example: one 4 Tb HDD and three 2 Tb HDD).

Popular P2P applications such as µTorrent or eMule would be able to share these files from their initial locations.

IPFS intends to copy files to its local storage (as far as I understand) and thus creates limitations:
- Two copies of a file exist, and thus the necessary disk space is doubled.
- IPFS local storage is limited by the size of its physical drive.

Is that a problem? Can IPFS work around that problem?

**Comment by RichardLitt** [comment]
I'm not sure. @noffle, what do you think?

**Comment by hackergrrl** [comment]
My understanding is that we copy on add, and that a great deal of users would like if we did otherwise. We're 100% interested in this happening. You can follow along in that discussion or suggest proposals for it on https://github.com/ipfs/go-ipfs/issues/875.

**Comment by Kubuxu** [comment]
It would be awesome to detect modern Copy on Write filesystems and then use different datastore method. Copy whole file, thus freeze it content without really copping it, start chunking it in memory saving only hashes and file offsets. This way we can add files to IPFS without doubling storage requirements.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/sharing-files-from-their-current-locations/361.
