### ISSUE TITLE
Mount IPFS as writable filesystem?

### ISSUE THREAD

**Issue by dpercy** [ipfs/faq#64]
Currently if you want to write a file to IPFS you have to do so explicitly, with either the command-line interface or the HTTP gateway.  By contrast, reading files works transparently when you mount /ipfs and /ipns.  

Will there be a way to transparently write files to IPFS through its mount point?  For example, suppose I wanted to use `/ipns/<hash-of-pubkey>` as a personal Dropbox.  I want to be able to `cd /ipns/<hash-of-pubkey> ; echo "hello new file" > file.txt`, and then have `/ipns/<hash-of-pubkey>/file.txt` become visible to other nodes.  Will an interface like this be a core feature of IPFS, or should this be a separate FUSE application written on top of IPFS?

**Comment by whyrusleeping** [comment]
have you tried doing the thing you suggest?

**Comment by dpercy** [comment]
Ha, I just noticed: https://github.com/ipfs/go-ipfs/issues/1007  This is awesome!

Sorry for the frivolous question; I could have investigated this more myself before posting.

**Comment by whyrusleeping** [comment]
@dpercy haha, no worries! i'm glad this is a feature people still want :+1: (warning though, i havent looked at that code in a good while and travis CI cant test fuse stuff for us)

**Comment by dpercy** [comment]
Is it possible for more than one node to write to the same directory?  I guess they would need to both have access to the same private key to update the ipns entry.  Is it possible to run IPFS nodes with identical keys on two separate machines?

**Comment by whyrusleeping** [comment]
that is planned, but not yet implemented. Its gonna be tricky to do right.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/mount-ipfs-as-writable-filesystem/439.

**Comment by novusabeo** [comment]
Does mounting require the use of IPNS? Can I mount without publishing -- assuming from the node with the key?

**Comment by balupton** [comment]
Can the IPFS team please lock all GitHub issues that have been moved elsewhere?

**Comment by novusabeo** [comment]
Why -- is IPFS finished? Is everything complete and good to go? I would imagine we want to leave as many channels open as possible

**Comment by balupton** [comment]
> Why -- is IPFS finished? Is everything complete and good to go? I would imagine we want to leave as many channels open as possible

Because this discussion has been moved here https://discuss.ipfs.io/t/mount-ipfs-as-writable-filesystem/439
