### ISSUE TITLE
ipfs.pics

### ISSUE THREAD

**Issue by paulransfield** [ipfs/faq#65]
i like this application of ipfs ... 

anyone know who are responsible for http://ipfs.pics/ ?

**Comment by whyrusleeping** [comment]
I only know their names from when they dropped by irc, vincent and didier. Other than that i'm not sure.

**Comment by whyrusleeping** [comment]
Oh, looks like they just open sourced it yesterday: https://github.com/ipfspics/server

It appears that @cloutier is at least partially responsible

**Comment by paulransfield** [comment]
thanks @whyrusleeping ... 

btw ... i love IPFS as a project ... and what you guys are doing with it ...

as an instructional designer ... i imagine that it wouldn't take much to dig a pipeline plan out of this github faq space ... 

anyway ... thanks for your prompt reply ... and all the very best for ipfs ...

http://gateway.ipfs.io/ipfs/QmPv9k6WMd49SEGrTJjm93t7WLPd63dTpDvJ1ox8dCahJm

**Comment by cloutier** [comment]
I'm glad you like it! :smile:

**Comment by whyrusleeping** [comment]
@cloutier congratz on open sourcing! your solution is much easier to use than imgur (not to mention being like, distributed and stuff)

**Comment by didiercf** [comment]
We had been looking forward to making it so (open source that is) and as it turns out it was a great decision. The community around IPFS is amazing!

**Comment by whyrusleeping** [comment]
@didiercf yeah, everyone around here seems to love tinkering with the code themselves. keeping everything open source has really made things a lot nicer.

**Comment by paulransfield** [comment]
hi @cloutier + @didiercf ... i've enjoyed using ipfs.pics ... and have shown it in the Open Bazaar slack ... 

good luck with adding functionality ... one of the requests in OB was for a bulk image uploader ...

i'm okay from the command line ... but for many, adding multiple files from a gui seems like a solution ...

**Comment by didiercf** [comment]
We will add a GUI in the upcoming weeks, there's still a lot of work to be done on it. But it's on our list!

**Comment by paulransfield** [comment]
cheers @didiercf ... by the way ... i like the gray background ... it suits my content ...

http://ipfs.pics/QmSGsXsqvTvXQxigV52kiiMRLHmWXuRgEPYZz6EFwhCAFQ

and keep in mind ... unsplash.com have had 10 million image downloads ... est 3m visits per month 

http://www.similarweb.com/website/unsplash.com#overview

(with no advertising, and i'm sure i read they had received $6m in funding)

**Comment by paulransfield** [comment]
@whyrusleeping @didiercf 

interesting ... ipfs.pics will display any IPFS hash ... not just ones uploaded to ipfs.pics

http://ipfs.pics/QmV2xVNBwhcLxnrNw1pczUVvWQ6iwNrAucuToKQ5Pwk9SQ
