### ISSUE TITLE
Could IPFS be run on I2P?

### ISSUE THREAD

**Issue by aaannndddyyy** [ipfs/faq#66]
Could IPFS be run on i2p?

**Comment by RichardLitt** [comment]
I don't know. Could you try? 

ping @whyrusleeping

**Comment by whyrusleeping** [comment]
You could likely run ipfs behind i2p, and make outbound connections to either other peers within i2p, or peers in the clearweb through i2p exit relay type nodes (my knowledge of i2p isnt perfect, but i'm pretty sure thats somewhat how things work).

The issue you would likely run into is that other nodes will have great difficulty dialing back to you, so inbound connections would be difficult. Its likely that with some sort of hidden service (like tor) things could work, but this question would be better answered by someone who knows more about i2p.

**Comment by geebotron** [comment]
So you mean objects inserted into the IPFS via a node that existed on the I2P network would have no means of propagating into the clearnet without some sort of an interface? Clearnet nodes would be addressable from inside I2P via an outproxy, but not the other way around.

The vuze bittorrent client developers seem to have [tackled this particular I2P problem](https://wiki.vuze.com/w/I2PHelper_HowTo#Network_Mixing)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/could-ipfs-be-run-on-i2p/492
