### ISSUE TITLE
ipfs file - meta data eg date created, uploaded, by

### ISSUE THREAD

**Issue by paulransfield** [ipfs/faq#67]
how do i find out who, when, and where an ipfs file was uploaded to ipfs?

i created this mockup of dogole a couple of weeks before google rebranded ...

but how can i tell i made it?

https://gateway.ipfs.io/ipfs/QmZYs66kvUZCkuCmSogANJCneKTTp2jLrBscsYTt2yKjhK

**Comment by jbenet** [comment]
all of that information is irrelevant to a low level object store -- it is metadata you want to track, which is doable but should not be enforced for all objects.

**Comment by jbenet** [comment]
btw, all the data will be manipulatable to some degree-- if you care about attribution, the real solution is to use something like ascribe -- https://ascribe.io

**Comment by paulransfield** [comment]
@jbenet thanks for your reply, advice and pointer to ascribe.io :)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-file-meta-data-eg-date-created-uploaded-by/452
