### ISSUE TITLE
Questions - 2014 Filecoin Paper and related IPFS 

### ISSUE THREAD

**Issue by MaxEntropyy** [ipfs/faq#68]
Hello...

I have recently read the 2014 Filecoin paper and I understand from the IPFS website that the Filecoin release will follow the V1.0 release of IPFS. I am considering the use of IPFS and possibly Filecoin in a telco communications environment for a modified type of messaging; and for high latency network file stores.

Several questions come to mind...

Questions:

Q1: is there an implementation of the Filecoin system?

Q2: if so, then have there been any performance analysis tests run that you can publish for file size boundary cases?

Q3: I am interested in Proof of Retrievability Challenges... Is there a discussion of the different cases to be considered?

Q4: I have looked for an implementation of the Gateway.ipfs.io executable and I don't believe it is at the IPFS Github repository. Did I miss it?

If there is a more appropriate place to ask these questions please direct me to that location.

With kind regards,
jds

**Comment by RichardLitt** [comment]
@MaxEntropyy Good questions. Sorry for the delay. 

Q1/2. Not yet. 
Q3. I think you might want to check github.com/ipfs/specs. There might be an answer in there. I'm personally not sure, at the moment
Q4. Yep: it is in [go-ipfs](//github.com/ipfs/go-ipfs), the current implementation. 

This is the right place, but we have not been the most timely. IRC is always faster.

**Comment by MaxEntropyy** [comment]
Thanks Richard

**Comment by RichardLitt** [comment]
No problem. Reopen as needed.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/questions-2014-filecoin-paper-and-related-ipfs/423
