### ISSUE TITLE
Multi net routing

### ISSUE THREAD

**Issue by chpio** [ipfs/faq#7]
Hi,

say im only reachable via IPv6, but many existing nodes are using IPv4. Is there something like a "gateway" that helps me to reach the IPv4 nodes? (IPv4/6 is just an example. It should also work with TOR, i2p, cjdns...)

**Comment by jbenet** [comment]
Yes, IPFS will be multi transport. Bridging between networks may break important properties of those networks (e.g. anonymity) so networks with important constraints will require careful design.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/multi-net-routing/458
