### ISSUE TITLE
How to solve the file transfer problem?

### ISSUE THREAD

**Issue by rht** [ipfs/faq#71]
https://xkcd.com/949/

Moved from https://github.com/ipfs/examples/issues/39.

**Comment by Mithgol** [comment]
(The answer is `ipfs add` on the source computer and then `ipfs get` on the destination.)

**Comment by rht** [comment]
(yes, very indeed, for the *nix neckbeards)

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/how-to-solve-the-file-transfer-problem/292.
