### ISSUE TITLE
ipfs + linkedin discussion re smart contracts

### ISSUE THREAD

**Issue by paulransfield** [ipfs/faq#72]
hi #team.ipfs ...

3 months ago i established a linkedin discussion group called 'smart contracts' ...

please consider contributing to those discussions relating to IPFS ...

https://www.linkedin.com/grp/home?gid=8360065

**Comment by RichardLitt** [comment]
Hi @paulransfield. This repository is only for questions about IPFS. Please let us know if you have any questions. Thanks.

**Comment by paulransfield** [comment]
Understood ... i'll close this issue.
