### ISSUE TITLE
can users POST things to the Permanent Web?

### ISSUE THREAD

**Issue by Mithgol** [ipfs/faq#73]
**— How do I host static content?**

— Publish it to IPFS using `ipfs add`.

**— How do I host non-static content that changes over time?**

— Use `ipfs name` to assign the same name to different versions of the content.

**— How do I host an interactive content that receives input from users? A forum or an imageboard where users are able to POST forms containing comments?**

— …

**Comment by chen-chan** [comment]
I'm not an expert but I've read there is a way for peers to talk directly to each other, not sure how it's actually done.

**Comment by hackergrrl** [comment]
@chen-chan: yes, it's possible to write services on top of some of IPFS' core components. [There's even an example](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmQwAP9vFjbCtKvD8RkJdCvPHqLQjZfW7Mqbbqx18zd8j7/api/service/readme.md)! Eventually this will be done with cleaner separation via [libp2p](https://github.com/ipfs/specs/tree/master/libp2p).

**Comment by fazo96** [comment]
> How do I host an interactive content that receives input from users? A forum or an imageboard where users are able to POST forms containing comments?

You might want to take a look at [IPFS Boards](https://github.com/fazo96/ipfs-boards). It's still very early, but it mostly works already :+1:

**Comment by Mithgol** [comment]
IPFS Boards' `README.md` from the `master` branch [currently](https://github.com/fazo96/ipfs-boards/blob/8c40432a9295b61eb468f09576d403dd7b0f8c20/README.md) says that it is outdated and the development happens on the [ipfs0.4](https://github.com/fazo96/ipfs-boards/tree/ipfs0.4) branch.

IPFS Boards' `README.md` from the `ipfs0.4` branch [currently](https://github.com/fazo96/ipfs-boards/blob/aecf89339c8a2eb9c82635a89b1406c44f129885/README.md) says that it uses IPFS's [POST](https://github.com/ipfs/POST) protocol.

[The repository of IPFS POST](https://github.com/ipfs/POST) currently contains only the initial commit that was necessary to create it on GitHub.

So, something is obviously on its way to the Go implementation of IPFS v0.4, and that something would probably resemble HTTP POST, but currently it's still underdocumented.

**Comment by fazo96** [comment]
> IPFS Boards' README.md from the ipfs0.4 branch currently says that it uses IPFS's POST protocol.

Well, actually it says it solves some problems _with the help of_ POST. :smile: 

If you think it's misleading, I'll probably change it though.

Work on POST needs to start, my app already has quite a few problems POST will face solved though, so we can take some inspiration from that I hope :smile:

**Comment by jbenet** [comment]
Indeed it does! i will have time in Feb for POST. we can do a kick off hangout first week of feb. ideally we can get to a very simple spec on top of IPLD. IPLD is already clear enough that we can do it.

take a look at this example for now: https://github.com/ipfs/ipld-examples/blob/master/post/example.yml
based on a format like what's in https://github.com/ipfs/POST/issues/6

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/can-users-post-things-to-the-permanent-web/308.
