### ISSUE TITLE
Does IPFS implement Robin fingerprint?

### ISSUE THREAD

**Issue by sivachandran** [ipfs/faq#74]
Tried adding a file multiple times after changing few bytes at the start. Every time the 'blocks' directory size increases by full size of the file I am adding. So wondering whether IPFS implements Robin fingerprint based blocking or is it in the roadmap.

**Comment by sivachandran** [comment]
Pasting answer from IRC.

**whyrusleeping:** we implement rabin fingerprinting, but its not in the default
**sivachandran:** how can I enable it?
**whyrusleeping:** ipfs add -s rabin <file>
**whyrusleeping:** you can also specify some parameters to rabin (this isnt well documented yet, i apologize)
**whyrusleeping:** example: set average block size: 'ipfs add -s rabin-128000 <file>'
**whyrusleeping:** and you can also set min and max block sizes at the same time: 'ipfs add -s rabin 256-4096-8192 <file>'
**whyrusleeping:** will try to make the average blocksize 4096, but force the blocks to be less than 8192 and greater than 256
**whyrusleeping:** sorry, '-s rabin-256-4096-8192'
**whyrusleeping:** needs to be a single string as the parameter

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/does-ipfs-implement-robin-fingerprint/481
