### ISSUE TITLE
Git-style Versioning 

### ISSUE THREAD

**Issue by jbenet** [ipfs/faq#75]
in IRC, rogueism asked:

> Is there a spec for the git-like system on IPFS?

I answered:

not quite yet. there's two paths: 
- (1) is importing/wrapping actual git. there's a few approaches to this, whyrusleeping made a git-http-clonable rehost https://github.com/whyrusleeping/git-ipfs-rehost -- cryptix made an _actual git remote_ plugin https://github.com/cryptix/git-remote-ipfs 
- (2) there's adding commits to ipfs. this has been meaning to happen for a while, but i wanted to get identity right first. that still hasnt happened, but we can now count on identity being objects, so we can probably implement https://github.com/ipfs/notes/issues/23 very soon

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/git-style-versioning/447
