### ISSUE TITLE
Why the name IPFS?

### ISSUE THREAD

**Issue by jbenet** [ipfs/faq#76]
The original name was GFS, which stood for the Global File System and seemed more accurate than GitFS. But that exact name was already [taken](http://en.wikipedia.org/wiki/GFS2). So I switched Global for Galactic, in an homage to Licklider's [Intergalactic Computer Network](http://en.wikipedia.org/wiki/Intergalactic_Computer_Network), and because peer-to-peer systems look like galaxies to me. But GFS caused confusion with yet another [GFS](http://en.wikipedia.org/wiki/Google_File_System), even though that one is not even open source.

By popular demand (there were votes and a pronouncement of "GFS is dead. Long live IPFS!" and everything), I switched it to IPFS - InterPlanetary File System, which has several nice properties:
- IP evokes the goal better: internet infrastructure
- InterPlanetary still pays an homage to Licklider
- [If all goes well](http://spacex.com), it may soon be InterPlanetary.
- Name clashes less.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/why-the-name-ipfs/307
