### ISSUE TITLE
I can not figure out how to add files or directory in Windows command line.

### ISSUE THREAD

**Issue by Shikibashi** [ipfs/faq#77]
ipfs add -r ./$dir F:\Documents\DOCUMENTs will not work, neither will ipfs add -r F:\Documents\DOCUMENTs which brings up Error: can't Lock file "C:\Users\tshef\.ipfs/repo.lock": has non-zero size.
What am I doing wrong here?

**Comment by jbenet** [comment]
Looks like a bug with the repo lock -- cc @whyrusleeping

**Comment by whyrusleeping** [comment]
looks like it, yeah. @Shikibashi do you have a repro?

**Comment by whyrusleeping** [comment]
also, can i get the output of `ipfs diag sys` in a gist?

**Comment by Shikibashi** [comment]
I do not think i have a repo. How would i check that?
I ran ipfs diag sys in the command line and i got the error: The system cannot find the path specified.

I restarted my computer and now ipfs add works. I do not know how that works, but it did.

**Comment by jbenet** [comment]
@Shikibashi try `ipfs init` ?

**Comment by ilyaigpetrov** [comment]
The same problem. Starting `ipfs daemon` resolves the lock.

**Comment by oshliaer** [comment]
Administrator privileges are required. Is there a way to avoid this?

``` sh
User@BIGPC MINGW64 /c
$ ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme
Error: can't Lock file "C:\\Users\\User\\.ipfs/repo.lock": has non-zero size
```

``` sh
User@BIGPC MINGW64 /c
$ ipfs daemon
Initializing daemon...
Error: can't Lock file "C:\\Users\\User\\.ipfs/repo.lock": has non-zero size
```

Never mind. My bash is broken [#irc](https://botbot.me/freenode/ipfs/2016-03-23/?msg=62782325&page=7)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/i-can-not-figure-out-how-to-add-files-or-directory-in-windows-command-line/390
