### ISSUE TITLE
Who designed IPFS?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/faq#78]
## Answer

IPFS is the brainchild of [Juan Benet](http://juan.benet.ai).

But IPFS has been designed by the internet at large. The ideas behind IPFS have been around for many years, in the form of excellent open source systems and research. If it gets far at all, IPFS will be standing on the wigs of giants.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/who-designed-ipfs/392
