### ISSUE TITLE
Creating an ephemeral IPFS node with consistent keypair

### ISSUE THREAD

**Issue by harlantwood** [ipfs/faq#79]
I plan to set up an IPFS node on Circle CI which has a consistent keypair, so it can sign IPNS records.  The node will be ephemeral; created fresh on each build.  My plan so far is to use https://github.com/ipfs/js-ipfsd-ctl to spin up a node, and set the public/private key from environment variables stored within Circle CI.  

Sound good?  Better ways to do any of this?

**Comment by harlantwood** [comment]
In IRC, @lgierth said:

> that sounds good to me

**Comment by jbenet** [comment]
SGTM too

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/creating-an-ephemeral-ipfs-node-with-consistent-keypair/384.
