### ISSUE TITLE
Once I add something to IPFS, will it remain available to others once I turn off my computer?

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/faq#8]
ipfs provides no guarantees about data availability or redundancy. Data added to ipfs is self hosted until another interested party decides to request it from you and rehost.

**Comment by jbenet** [comment]
this is what IPFS sister project [filecoin](http://filecoin.io) is for.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/once-i-add-something-to-ipfs-will-it-remain-available-to-others-once-i-turn-off-my-computer/397.
