### ISSUE TITLE
Does IPFS (the protocol, not an implementation) have a license?

### ISSUE THREAD

**Issue by doesntgolf** [ipfs/faq#80]
I'm not sure if it even makes sense for protocols to be licensed, so I'm trying to understand it better. (After a quick googling I haven't been able to determine if HTTP has a license, so I'm guessing it doesn't. The only writing about protocol licenses I could find is [this blog post](http://hintjens.com/blog:41).)

**Comment by jbenet** [comment]
good question. i was not familiar with the implications of licenses on the protocol itself. good link, thanks. i'll look into this in the coming weeks. likely will be licensed permissively, though i do want to run that question by people at the IETF and W3C.

**Comment by JesseWeinstein** [comment]
Any update on this?

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/does-ipfs-the-protocol-not-an-implementation-have-a-license/405.
