### ISSUE TITLE
Making files Searchable

### ISSUE THREAD

**Issue by coakeson** [ipfs/faq#81]
Any plans on making files searchable?

**Comment by alexpear** [comment]
There are plans to make files globally addressible via IPNS, Namecoin, or other systems, but that's not quite the same thing. I know some other projects such as alexandria.media are making searchable databases that use IPFS on the backend. 

Others might know more than i do.

**Comment by alexpear** [comment]
one of presumably many threads about this topic: https://github.com/ipfs/archives/issues/8

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/making-files-searchable/454
