### ISSUE TITLE
IPFS  DNS / gateway

### ISSUE THREAD

**Issue by shalnoff** [ipfs/faq#84]
Is it possible to run own Name Server (hint for OpenNicProject) that would accept IPFS addreses as NS records and resolve non ICANN domains for IPFS filespace? 

Or/and maybe gateway for classical ICANN domains?

**Comment by RichardLitt** [comment]
ping @lgierth

**Comment by Kubuxu** [comment]
IPFS uses system DNS resolution settings and has its limiting lists of TLDs (which I don't know if it is good idea), the list is here: https://github.com/jbenet/go-is-domain/blob/master/tlds.go

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/ipfs-dns-gateway/368.
