### ISSUE TITLE
IPFS replication factor

### ISSUE THREAD

**Issue by sciffer** [ipfs/faq#89]
Does IPFS have builtin replication factor, so that I can be sure that all my files will be available even if a server of mine goes down?
I would like to be able to have availability between a group of servers (without necessarily to query the files for caching - something more suitable for availability of the content itself regardless of caching and whether caching is emptied/overwritten).

**Comment by ghost** [comment]
It doesn't at the moment, but the ipfs-cluster tool will offer various ways of pinning objects on multiple nodes: https://github.com/ipfs/notes/issues/58

Let me know if you have more questions about this, or close the issue otherwise :)

**Comment by whyrusleeping** [comment]
see #8

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-replication-factor/479
