### ISSUE TITLE
How can I set my node's location?

### ISSUE THREAD

**Issue by Azulan** [ipfs/faq#91]
How can I configure the node to share what City or Country I'm in?

**Comment by lidel** [comment]
These values are [tied to the IP](https://en.wikipedia.org/wiki/Geolocation_software) you use:

Example: http://freegeoip.net/json/8.8.8.8

**Comment by meulie** [comment]
But what if this info is incorrect/inaccurate? Is there a way to tune this?

**Comment by lidel** [comment]
I think you need to find out which [data provider](https://en.wikipedia.org/wiki/Geolocation_software#Data_sources) manages your IP range and contact them directly.

As far I know update may take from a few weeks to months.

**Comment by RichardLitt** [comment]
@whyrusleeping How would you do this? Or @dignifiedquire, do you know?

**Comment by whyrusleeping** [comment]
The answer given by @lidel is correct.

**Comment by alexanderattar** [comment]
Does anyone know what would cause the location to be unknown? I set up a remote node and using the tool @lidel gave above (http://freegeoip.net/json/), I have confirmed that the IP location is in New York, but when I visit the webui on the node info page, I see that the location is unknown, and that the node is also not connected to any peers. I'm wondering if I've missed something as far as configuration goes. Thanks in advance!

**Comment by Kubuxu** [comment]
The GeoIP database we use was not updated for a long time so some IPs might have wrong/unknown locations.

If you are getting no peers it might be NAT/firewall configuration problem. There are other issues on that too.

**Comment by alexanderattar** [comment]
Ah okay. Thanks for the response @Kubuxu! That sounds like it could be the cause of the unknown location. I do not have any firewall at the moment so the node should be open for connections. I am able to see peers in the console via `ipfs swarm peers` so perhaps it is just an issue with the webui? I can open a new issue if that seems to be the case.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-can-i-set-my-nodes-location/367
