### ISSUE TITLE
Public facing gateway and pinning

### ISSUE THREAD

**Issue by Kolomona** [ipfs/faq#94]
If I have a public facing gateway and a person retrieves a file through it. Does the file get pinned into my gateway or does the data just pass through without getting pinned? Thanks

**Comment by ghost** [comment]
Your gateway fetches and stores the data, but doesn't pin it. It gets removed with the next garbage collection run.

**Comment by Kolomona** [comment]
Thank you for your answer. 
Does this mean that if someone were to retrieve illegal content through my public gateway then my ipfs instance would be storing and serving the illegal content until it is garbage collected?

If this is true then it seems to be a potential liability issue.

**Comment by Kubuxu** [comment]
This is what you get running a public gateway. Either way someone could download illegal content from it which implies that this content would pass through your machine.

There are works to make opt-in badbits lists which would block illegal contented .

**Comment by Kolomona** [comment]
Personally, I don't believe that intellectual property exists as an actual property right, but my opinion will not stop the "Department of Making you Sad" from throwing me into a cage for distributing so called intellectual property.

The opt-in list is a good idea to minimize legal liability for the users as well as the IPFS project itself. There are so many useful and legal services that can be made from a system like IPFS. I believe that IPFS is an amazing technology and I really want it to succeed.

If you are curious about why I believe the way I do then read:
https://mises.org/library/against-intellectual-property-0

**Comment by Musickiller** [comment]
any guides on how to create public facing gateway? please!

**Comment by salsa-dev** [comment]
> any guides on how to create public facing gateway? please!

I suppose you just install ipfs node and make nginx proxy to it, right?

**Comment by Kubuxu** [comment]
Yes, also enable garbage colection in config, I don't think it is enabled by default (or run it manually in cron/timer job once a day, few hours or something).

**Comment by Musickiller** [comment]
Thanks. I've already done it with some other app, but encountered a problem with my ports. They just don't open, no matter what I do. But it's not a problem with IPFS, so it's OK)) Bye!

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/public-facing-gateway-and-pinning/449.
