### ISSUE TITLE
When initialising IPFS, terminal says "permission denied"

### ISSUE THREAD

**Issue by bierlingm** [ipfs/faq#96]
<img width="711" alt="screen shot 2016-02-17 at 18 31 00" src="https://cloud.githubusercontent.com/assets/9335771/13125511/b0a6a092-d5a4-11e5-8af3-0d7e0785f46c.png">

**Comment by ghost** [comment]
You probably need to set executable permissions on `ipfs`: `chmod +x /usr/local/bin/ipfs`

Please reopen if this doesn't help.

**Comment by bierlingm** [comment]
How do I do that?

**Comment by ghost** [comment]
Right there in the terminal where you got the permissions error, you do: `chmod +x /usr/local/bin/ipfs`

**Comment by bierlingm** [comment]
<img width="594" alt="screen shot 2016-02-17 at 18 39 22" src="https://cloud.githubusercontent.com/assets/9335771/13125698/d32dbabe-d5a5-11e5-9fe7-eaac47bc1f54.png">
<img width="491" alt="screen shot 2016-02-17 at 18 39 32" src="https://cloud.githubusercontent.com/assets/9335771/13125704/d8350cba-d5a5-11e5-9050-e4de85954a2c.png">

**Comment by ghost** [comment]
Just this: `chmod +x /usr/local/bin/ipfs`

**Comment by bierlingm** [comment]
![](https://cloud.githubusercontent.com/assets/9335771/13125704/d8350cba-d5a5-11e5-9050-e4de85954a2c.png)

I just did that, but the init command doesn't work. Thanks for your help, btw!

**Comment by ghost** [comment]
`ipfs` might not be in your PATH environment variable. Try executing with the full path: `/usr/local/bin/init` (if that's where you copied it to)

**Comment by bierlingm** [comment]
Thanks, I've got it now!
