### ISSUE TITLE
Protocol for arbitrary metadata?

### ISSUE THREAD

**Issue by micahredding** [ipfs/faq#98]
I haven't seen any docs on this, so I'm assuming this isn't in place — but is there an established protocol for attaching arbitrary metadata to files? Does `ipfs add` support any metadata options?

**Comment by RichardLitt** [comment]
I'm not sure. You might want to check in github.com/ipfs/specs.

**Comment by hackergrrl** [comment]
IPFS stores _objects_, where _files_ are a data structure on top. (Easy misconception, given the project name :smile:). Take a look at `ipfs object --help` for some commands that assist in building custom object structures using IPFS merkle dag objects.

Soon we'll be using a format called [IPLD](https://github.com/ipfs/specs/blob/master/merkledag/ipld.md), which will make it easier to describe arbitrary data structures on top of IPFS.

**Comment by whyrusleeping** [comment]
Ipfs files currently do have a metadata object, but we havent put a lot of effort into it yet and using it is rather difficult.

That said, the current metadata structure is here: https://github.com/ipfs/go-ipfs/blob/master/unixfs/format.go#L180

Right now it only has fields for a mime type and size, but i think adding arbitrary key/value pairs to that is probably something good to do in the short term (before IPLD is done).

We should also work on exposing that metadata object through `ipfs add` and friends.

**Comment by madavieb** [comment]
This issue has been moved to https://discuss.ipfs.io/t/protocol-for-arbitrary-metadata/346.
